// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/didrikolofsson/github-vote-llm/internal/hub (interfaces: Hub)
//
// Generated by this command:
//
//	mockgen -destination=internal/hub/mock_hub.go -package=hub github.com/didrikolofsson/github-vote-llm/internal/hub Hub
//

// Package hub is a generated GoMock package.
package hub

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHub is a mock of Hub interface.
type MockHub struct {
	ctrl     *gomock.Controller
	recorder *MockHubMockRecorder
	isgomock struct{}
}

// MockHubMockRecorder is the mock recorder for MockHub.
type MockHubMockRecorder struct {
	mock *MockHub
}

// NewMockHub creates a new mock instance.
func NewMockHub(ctrl *gomock.Controller) *MockHub {
	mock := &MockHub{ctrl: ctrl}
	mock.recorder = &MockHubMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHub) EXPECT() *MockHubMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockHub) Publish(repoID int64, event EventType) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Publish", repoID, event)
}

// Publish indicates an expected call of Publish.
func (mr *MockHubMockRecorder) Publish(repoID, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockHub)(nil).Publish), repoID, event)
}

// PublishOrg mocks base method.
func (m *MockHub) PublishOrg(orgID int64, event EventType) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PublishOrg", orgID, event)
}

// PublishOrg indicates an expected call of PublishOrg.
func (mr *MockHubMockRecorder) PublishOrg(orgID, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishOrg", reflect.TypeOf((*MockHub)(nil).PublishOrg), orgID, event)
}

// Subscribe mocks base method.
func (m *MockHub) Subscribe(repoID int64) chan EventType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", repoID)
	ret0, _ := ret[0].(chan EventType)
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockHubMockRecorder) Subscribe(repoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockHub)(nil).Subscribe), repoID)
}

// SubscribeOrg mocks base method.
func (m *MockHub) SubscribeOrg(orgID int64) chan EventType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeOrg", orgID)
	ret0, _ := ret[0].(chan EventType)
	return ret0
}

// SubscribeOrg indicates an expected call of SubscribeOrg.
func (mr *MockHubMockRecorder) SubscribeOrg(orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeOrg", reflect.TypeOf((*MockHub)(nil).SubscribeOrg), orgID)
}

// Unsubscribe mocks base method.
func (m *MockHub) Unsubscribe(repoID int64, ch chan EventType) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unsubscribe", repoID, ch)
}

// Unsubscribe indicates an expected call of Unsubscribe.
func (mr *MockHubMockRecorder) Unsubscribe(repoID, ch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockHub)(nil).Unsubscribe), repoID, ch)
}

// UnsubscribeOrg mocks base method.
func (m *MockHub) UnsubscribeOrg(orgID int64, ch chan EventType) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UnsubscribeOrg", orgID, ch)
}

// UnsubscribeOrg indicates an expected call of UnsubscribeOrg.
func (mr *MockHubMockRecorder) UnsubscribeOrg(orgID, ch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnsubscribeOrg", reflect.TypeOf((*MockHub)(nil).UnsubscribeOrg), orgID, ch)
}
