// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feature_comments.sql

package store

import (
	"context"
)

const createFeatureComment = `-- name: CreateFeatureComment :one
INSERT INTO feature_comments (feature_id, body, author_name)
VALUES ($1, $2, $3)
RETURNING id, feature_id, body, author_name, created_at
`

type CreateFeatureCommentParams struct {
	FeatureID  int64
	Body       string
	AuthorName string
}

func (q *Queries) CreateFeatureComment(ctx context.Context, arg CreateFeatureCommentParams) (FeatureComment, error) {
	row := q.db.QueryRow(ctx, createFeatureComment, arg.FeatureID, arg.Body, arg.AuthorName)
	var i FeatureComment
	err := row.Scan(
		&i.ID,
		&i.FeatureID,
		&i.Body,
		&i.AuthorName,
		&i.CreatedAt,
	)
	return i, err
}

const listFeatureComments = `-- name: ListFeatureComments :many
SELECT id, feature_id, body, author_name, created_at FROM feature_comments
WHERE feature_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListFeatureComments(ctx context.Context, featureID int64) ([]FeatureComment, error) {
	rows, err := q.db.Query(ctx, listFeatureComments, featureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeatureComment
	for rows.Next() {
		var i FeatureComment
		if err := rows.Scan(
			&i.ID,
			&i.FeatureID,
			&i.Body,
			&i.AuthorName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
