// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: features.sql

package store

import (
	"context"
)

const createFeature = `-- name: CreateFeature :one
INSERT INTO features (repository_id, title, description)
VALUES ($1, $2, $3)
RETURNING id, repository_id, title, description, status, area, roadmap_x, roadmap_y, roadmap_locked, created_at, updated_at
`

type CreateFeatureParams struct {
	RepositoryID int64
	Title        string
	Description  string
}

func (q *Queries) CreateFeature(ctx context.Context, arg CreateFeatureParams) (Feature, error) {
	row := q.db.QueryRow(ctx, createFeature, arg.RepositoryID, arg.Title, arg.Description)
	var i Feature
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Area,
		&i.RoadmapX,
		&i.RoadmapY,
		&i.RoadmapLocked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFeature = `-- name: DeleteFeature :exec
DELETE FROM features WHERE id = $1
`

func (q *Queries) DeleteFeature(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteFeature, id)
	return err
}

const getFeature = `-- name: GetFeature :one
SELECT id, repository_id, title, description, status, area, roadmap_x, roadmap_y, roadmap_locked, created_at, updated_at FROM features WHERE id = $1
`

func (q *Queries) GetFeature(ctx context.Context, id int64) (Feature, error) {
	row := q.db.QueryRow(ctx, getFeature, id)
	var i Feature
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Area,
		&i.RoadmapX,
		&i.RoadmapY,
		&i.RoadmapLocked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFeatures = `-- name: ListFeatures :many
SELECT id, repository_id, title, description, status, area, roadmap_x, roadmap_y, roadmap_locked, created_at, updated_at FROM features
WHERE repository_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListFeatures(ctx context.Context, repositoryID int64) ([]Feature, error) {
	rows, err := q.db.Query(ctx, listFeatures, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feature
	for rows.Next() {
		var i Feature
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Area,
			&i.RoadmapX,
			&i.RoadmapY,
			&i.RoadmapLocked,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFeatureArea = `-- name: UpdateFeatureArea :one
UPDATE features SET area = $2, updated_at = now()
WHERE id = $1 RETURNING id, repository_id, title, description, status, area, roadmap_x, roadmap_y, roadmap_locked, created_at, updated_at
`

type UpdateFeatureAreaParams struct {
	ID   int64
	Area *string
}

func (q *Queries) UpdateFeatureArea(ctx context.Context, arg UpdateFeatureAreaParams) (Feature, error) {
	row := q.db.QueryRow(ctx, updateFeatureArea, arg.ID, arg.Area)
	var i Feature
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Area,
		&i.RoadmapX,
		&i.RoadmapY,
		&i.RoadmapLocked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFeaturePosition = `-- name: UpdateFeaturePosition :one
UPDATE features
SET roadmap_x = $2, roadmap_y = $3, roadmap_locked = $4, updated_at = now()
WHERE id = $1 RETURNING id, repository_id, title, description, status, area, roadmap_x, roadmap_y, roadmap_locked, created_at, updated_at
`

type UpdateFeaturePositionParams struct {
	ID            int64
	RoadmapX      *float64
	RoadmapY      *float64
	RoadmapLocked bool
}

func (q *Queries) UpdateFeaturePosition(ctx context.Context, arg UpdateFeaturePositionParams) (Feature, error) {
	row := q.db.QueryRow(ctx, updateFeaturePosition,
		arg.ID,
		arg.RoadmapX,
		arg.RoadmapY,
		arg.RoadmapLocked,
	)
	var i Feature
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Area,
		&i.RoadmapX,
		&i.RoadmapY,
		&i.RoadmapLocked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFeatureStatus = `-- name: UpdateFeatureStatus :one
UPDATE features SET status = $2, updated_at = now()
WHERE id = $1 RETURNING id, repository_id, title, description, status, area, roadmap_x, roadmap_y, roadmap_locked, created_at, updated_at
`

type UpdateFeatureStatusParams struct {
	ID     int64
	Status FeatureStatus
}

func (q *Queries) UpdateFeatureStatus(ctx context.Context, arg UpdateFeatureStatusParams) (Feature, error) {
	row := q.db.QueryRow(ctx, updateFeatureStatus, arg.ID, arg.Status)
	var i Feature
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Area,
		&i.RoadmapX,
		&i.RoadmapY,
		&i.RoadmapLocked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
