// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: features.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFeature = `-- name: CreateFeature :one
INSERT INTO features (
    repository_id,
    title,
    description,
    review_status,
    build_status
  )
VALUES ($1, $2, $3, $4, $5)
RETURNING id, repository_id, title, description, area, roadmap_x, roadmap_y, roadmap_locked, created_at, updated_at, review_status, build_status
`

type CreateFeatureParams struct {
	RepositoryID int64
	Title        string
	Description  string
	ReviewStatus ReviewStatusType
	BuildStatus  NullBuildStatusType
}

func (q *Queries) CreateFeature(ctx context.Context, arg CreateFeatureParams) (Feature, error) {
	row := q.db.QueryRow(ctx, createFeature,
		arg.RepositoryID,
		arg.Title,
		arg.Description,
		arg.ReviewStatus,
		arg.BuildStatus,
	)
	var i Feature
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Title,
		&i.Description,
		&i.Area,
		&i.RoadmapX,
		&i.RoadmapY,
		&i.RoadmapLocked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReviewStatus,
		&i.BuildStatus,
	)
	return i, err
}

const deleteFeature = `-- name: DeleteFeature :exec
DELETE FROM features
WHERE id = $1
`

func (q *Queries) DeleteFeature(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteFeature, id)
	return err
}

const getFeature = `-- name: GetFeature :one
SELECT id, repository_id, title, description, area, roadmap_x, roadmap_y, roadmap_locked, created_at, updated_at, review_status, build_status
FROM features
WHERE id = $1
`

func (q *Queries) GetFeature(ctx context.Context, id int64) (Feature, error) {
	row := q.db.QueryRow(ctx, getFeature, id)
	var i Feature
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Title,
		&i.Description,
		&i.Area,
		&i.RoadmapX,
		&i.RoadmapY,
		&i.RoadmapLocked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReviewStatus,
		&i.BuildStatus,
	)
	return i, err
}

const listFeatures = `-- name: ListFeatures :many
SELECT id, repository_id, title, description, area, roadmap_x, roadmap_y, roadmap_locked, created_at, updated_at, review_status, build_status
FROM features
WHERE repository_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListFeatures(ctx context.Context, repositoryID int64) ([]Feature, error) {
	rows, err := q.db.Query(ctx, listFeatures, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feature
	for rows.Next() {
		var i Feature
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.Title,
			&i.Description,
			&i.Area,
			&i.RoadmapX,
			&i.RoadmapY,
			&i.RoadmapLocked,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReviewStatus,
			&i.BuildStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeaturesForPortal = `-- name: ListFeaturesForPortal :many
SELECT f.id, f.repository_id, f.title, f.description, f.area, f.roadmap_x, f.roadmap_y, f.roadmap_locked, f.created_at, f.updated_at, f.review_status, f.build_status,
  COUNT(fv.id) AS vote_count
FROM features f
  LEFT JOIN feature_votes fv ON fv.feature_id = f.id
WHERE f.repository_id = $1
  AND f.review_status = 'approved'
GROUP BY f.id
ORDER BY vote_count DESC,
  f.created_at DESC
`

type ListFeaturesForPortalRow struct {
	ID            int64
	RepositoryID  int64
	Title         string
	Description   string
	Area          *string
	RoadmapX      *float64
	RoadmapY      *float64
	RoadmapLocked bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	ReviewStatus  ReviewStatusType
	BuildStatus   NullBuildStatusType
	VoteCount     int64
}

func (q *Queries) ListFeaturesForPortal(ctx context.Context, repositoryID int64) ([]ListFeaturesForPortalRow, error) {
	rows, err := q.db.Query(ctx, listFeaturesForPortal, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFeaturesForPortalRow
	for rows.Next() {
		var i ListFeaturesForPortalRow
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.Title,
			&i.Description,
			&i.Area,
			&i.RoadmapX,
			&i.RoadmapY,
			&i.RoadmapLocked,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReviewStatus,
			&i.BuildStatus,
			&i.VoteCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patchFeature = `-- name: PatchFeature :one
UPDATE features
SET title = COALESCE($1::text, title),
  description = COALESCE($2::text, description),
  review_status = COALESCE(
    $3::review_status_type,
    review_status
  ),
  build_status = COALESCE(
    $4::build_status_type,
    build_status
  ),
  area = COALESCE($5::text, area),
  updated_at = now()
WHERE id = $6
RETURNING id, repository_id, title, description, area, roadmap_x, roadmap_y, roadmap_locked, created_at, updated_at, review_status, build_status
`

type PatchFeatureParams struct {
	Title        *string
	Description  *string
	ReviewStatus NullReviewStatusType
	BuildStatus  NullBuildStatusType
	Area         *string
	ID           int64
}

func (q *Queries) PatchFeature(ctx context.Context, arg PatchFeatureParams) (Feature, error) {
	row := q.db.QueryRow(ctx, patchFeature,
		arg.Title,
		arg.Description,
		arg.ReviewStatus,
		arg.BuildStatus,
		arg.Area,
		arg.ID,
	)
	var i Feature
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Title,
		&i.Description,
		&i.Area,
		&i.RoadmapX,
		&i.RoadmapY,
		&i.RoadmapLocked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReviewStatus,
		&i.BuildStatus,
	)
	return i, err
}

const updateFeaturePosition = `-- name: UpdateFeaturePosition :one
UPDATE features
SET roadmap_x = $2,
  roadmap_y = $3,
  roadmap_locked = $4,
  updated_at = now()
WHERE id = $1
RETURNING id, repository_id, title, description, area, roadmap_x, roadmap_y, roadmap_locked, created_at, updated_at, review_status, build_status
`

type UpdateFeaturePositionParams struct {
	ID            int64
	RoadmapX      *float64
	RoadmapY      *float64
	RoadmapLocked bool
}

func (q *Queries) UpdateFeaturePosition(ctx context.Context, arg UpdateFeaturePositionParams) (Feature, error) {
	row := q.db.QueryRow(ctx, updateFeaturePosition,
		arg.ID,
		arg.RoadmapX,
		arg.RoadmapY,
		arg.RoadmapLocked,
	)
	var i Feature
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Title,
		&i.Description,
		&i.Area,
		&i.RoadmapX,
		&i.RoadmapY,
		&i.RoadmapLocked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReviewStatus,
		&i.BuildStatus,
	)
	return i, err
}
