// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feature_runs.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRun = `-- name: CreateRun :one
INSERT INTO
    feature_runs (
        prompt,
        feature_id,
        status,
        created_by_user_id,
        workspace
    )
VALUES ($1, $2, $3, $4, $5)
RETURNING
    id, prompt, feature_id, status, created_by_user_id, created_at, completed_at, workspace, pr_url, pid
`

type CreateRunParams struct {
	Prompt          string
	FeatureID       int64
	Status          FeatureRunStatus
	CreatedByUserID int64
	Workspace       string
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (FeatureRun, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.Prompt,
		arg.FeatureID,
		arg.Status,
		arg.CreatedByUserID,
		arg.Workspace,
	)
	var i FeatureRun
	err := row.Scan(
		&i.ID,
		&i.Prompt,
		&i.FeatureID,
		&i.Status,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.Workspace,
		&i.PrUrl,
		&i.Pid,
	)
	return i, err
}

const deleteCancelledRun = `-- name: DeleteCancelledRun :exec
DELETE FROM feature_runs WHERE id = $1 AND status IN ('cancelled', 'failed')
`

func (q *Queries) DeleteCancelledRun(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCancelledRun, id)
	return err
}

const getRunByID = `-- name: GetRunByID :one
SELECT
    fr.id, fr.prompt, fr.feature_id, fr.status, fr.created_by_user_id, fr.created_at, fr.completed_at, fr.workspace, fr.pr_url, fr.pid,
    r.id AS repository_id,
    r.organization_id AS organization_id,
    r.name AS repository_name,
    r.owner AS repository_owner
FROM
    organization_repositories AS r
    INNER JOIN features AS f ON f.repository_id = r.id
    INNER JOIN feature_runs AS fr ON fr.feature_id = f.id
WHERE
    fr.id = $1
`

type GetRunByIDRow struct {
	ID              int64
	Prompt          string
	FeatureID       int64
	Status          FeatureRunStatus
	CreatedByUserID int64
	CreatedAt       pgtype.Timestamptz
	CompletedAt     pgtype.Timestamptz
	Workspace       string
	PrUrl           *string
	Pid             *int32
	RepositoryID    int64
	OrganizationID  int64
	RepositoryName  string
	RepositoryOwner string
}

func (q *Queries) GetRunByID(ctx context.Context, id int64) (GetRunByIDRow, error) {
	row := q.db.QueryRow(ctx, getRunByID, id)
	var i GetRunByIDRow
	err := row.Scan(
		&i.ID,
		&i.Prompt,
		&i.FeatureID,
		&i.Status,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.Workspace,
		&i.PrUrl,
		&i.Pid,
		&i.RepositoryID,
		&i.OrganizationID,
		&i.RepositoryName,
		&i.RepositoryOwner,
	)
	return i, err
}

const listRunsByRepository = `-- name: ListRunsByRepository :many
SELECT
    fr.id,
    fr.prompt,
    fr.feature_id,
    fr.status,
    fr.created_by_user_id,
    fr.created_at,
    fr.completed_at,
    NULL::TEXT AS pr_url
FROM
    feature_runs AS fr
    INNER JOIN features AS f ON f.id = fr.feature_id
WHERE
    f.repository_id = $1
ORDER BY
    fr.created_at DESC
`

type ListRunsByRepositoryRow struct {
	ID              int64
	Prompt          string
	FeatureID       int64
	Status          FeatureRunStatus
	CreatedByUserID int64
	CreatedAt       pgtype.Timestamptz
	CompletedAt     pgtype.Timestamptz
	PrUrl           *string
}

func (q *Queries) ListRunsByRepository(ctx context.Context, repositoryID int64) ([]ListRunsByRepositoryRow, error) {
	rows, err := q.db.Query(ctx, listRunsByRepository, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunsByRepositoryRow
	for rows.Next() {
		var i ListRunsByRepositoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Prompt,
			&i.FeatureID,
			&i.Status,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.PrUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRunCancelled = `-- name: SetRunCancelled :exec
UPDATE feature_runs SET status = 'cancelled', completed_at = now() WHERE id = $1
`

func (q *Queries) SetRunCancelled(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, setRunCancelled, id)
	return err
}

const updateRunPID = `-- name: UpdateRunPID :exec
UPDATE feature_runs SET pid = $1 WHERE id = $2
`

type UpdateRunPIDParams struct {
	Pid *int32
	ID  int64
}

func (q *Queries) UpdateRunPID(ctx context.Context, arg UpdateRunPIDParams) error {
	_, err := q.db.Exec(ctx, updateRunPID, arg.Pid, arg.ID)
	return err
}

const updateRunPRURL = `-- name: UpdateRunPRURL :exec
UPDATE feature_runs SET pr_url = $1 WHERE id = $2
`

type UpdateRunPRURLParams struct {
	PrUrl *string
	ID    int64
}

func (q *Queries) UpdateRunPRURL(ctx context.Context, arg UpdateRunPRURLParams) error {
	_, err := q.db.Exec(ctx, updateRunPRURL, arg.PrUrl, arg.ID)
	return err
}

const updateRunStatus = `-- name: UpdateRunStatus :exec
UPDATE feature_runs SET status = $1, completed_at = CASE WHEN $1::feature_run_status IN ('completed', 'failed', 'cancelled') THEN now() ELSE completed_at END WHERE id = $2
`

type UpdateRunStatusParams struct {
	Status FeatureRunStatus
	ID     int64
}

func (q *Queries) UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) error {
	_, err := q.db.Exec(ctx, updateRunStatus, arg.Status, arg.ID)
	return err
}
