// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feature_dependencies.sql

package store

import (
	"context"
)

const addFeatureDependency = `-- name: AddFeatureDependency :exec
INSERT INTO feature_dependencies (feature_id, depends_on)
VALUES ($1, $2)
`

type AddFeatureDependencyParams struct {
	FeatureID int64
	DependsOn int64
}

func (q *Queries) AddFeatureDependency(ctx context.Context, arg AddFeatureDependencyParams) error {
	_, err := q.db.Exec(ctx, addFeatureDependency, arg.FeatureID, arg.DependsOn)
	return err
}

const listFeatureDependencies = `-- name: ListFeatureDependencies :many
SELECT feature_id, depends_on FROM feature_dependencies WHERE feature_id = $1
`

func (q *Queries) ListFeatureDependencies(ctx context.Context, featureID int64) ([]FeatureDependency, error) {
	rows, err := q.db.Query(ctx, listFeatureDependencies, featureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeatureDependency
	for rows.Next() {
		var i FeatureDependency
		if err := rows.Scan(&i.FeatureID, &i.DependsOn); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeatureDependenciesForRepository = `-- name: ListFeatureDependenciesForRepository :many
SELECT feature_id, depends_on FROM feature_dependencies
WHERE feature_id IN (SELECT id FROM features WHERE repository_id = $1)
`

func (q *Queries) ListFeatureDependenciesForRepository(ctx context.Context, repositoryID int64) ([]FeatureDependency, error) {
	rows, err := q.db.Query(ctx, listFeatureDependenciesForRepository, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeatureDependency
	for rows.Next() {
		var i FeatureDependency
		if err := rows.Scan(&i.FeatureID, &i.DependsOn); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFeatureDependency = `-- name: RemoveFeatureDependency :exec
DELETE FROM feature_dependencies
WHERE feature_id = $1 AND depends_on = $2
`

type RemoveFeatureDependencyParams struct {
	FeatureID int64
	DependsOn int64
}

func (q *Queries) RemoveFeatureDependency(ctx context.Context, arg RemoveFeatureDependencyParams) error {
	_, err := q.db.Exec(ctx, removeFeatureDependency, arg.FeatureID, arg.DependsOn)
	return err
}
