// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: github_connections.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addInstallationRepository = `-- name: AddInstallationRepository :exec
INSERT INTO github_installation_repositories (
        installation_id,
        github_repository_id,
        repository_name,
        repository_full_name
    )
VALUES ($1, $2, $3, $4) ON CONFLICT (installation_id, github_repository_id) DO
UPDATE
SET repository_name = EXCLUDED.repository_name,
    repository_full_name = EXCLUDED.repository_full_name
`

type AddInstallationRepositoryParams struct {
	InstallationID     int64
	GithubRepositoryID int64
	RepositoryName     string
	RepositoryFullName string
}

func (q *Queries) AddInstallationRepository(ctx context.Context, arg AddInstallationRepositoryParams) error {
	_, err := q.db.Exec(ctx, addInstallationRepository,
		arg.InstallationID,
		arg.GithubRepositoryID,
		arg.RepositoryName,
		arg.RepositoryFullName,
	)
	return err
}

const clearInstallationRepositories = `-- name: ClearInstallationRepositories :exec
DELETE FROM github_installation_repositories
WHERE installation_id = $1
`

func (q *Queries) ClearInstallationRepositories(ctx context.Context, installationID int64) error {
	_, err := q.db.Exec(ctx, clearInstallationRepositories, installationID)
	return err
}

const deleteInstallationByGithubID = `-- name: DeleteInstallationByGithubID :exec
DELETE FROM github_installations
WHERE github_installation_id = $1
`

func (q *Queries) DeleteInstallationByGithubID(ctx context.Context, githubInstallationID int64) error {
	_, err := q.db.Exec(ctx, deleteInstallationByGithubID, githubInstallationID)
	return err
}

const deleteInstallationByID = `-- name: DeleteInstallationByID :exec
DELETE FROM github_installations
WHERE id = $1
`

func (q *Queries) DeleteInstallationByID(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteInstallationByID, id)
	return err
}

const deleteInstallationByOrgID = `-- name: DeleteInstallationByOrgID :exec
DELETE FROM github_installations
WHERE organization_id = $1
`

func (q *Queries) DeleteInstallationByOrgID(ctx context.Context, organizationID int64) error {
	_, err := q.db.Exec(ctx, deleteInstallationByOrgID, organizationID)
	return err
}

const getInstallationByGithubID = `-- name: GetInstallationByGithubID :one
SELECT id, organization_id, github_installation_id, github_account_login, github_account_id, github_account_type, repository_selection, suspended_at, installed_by_user_id, created_at, updated_at, state
FROM github_installations
WHERE github_installation_id = $1
`

func (q *Queries) GetInstallationByGithubID(ctx context.Context, githubInstallationID int64) (GithubInstallation, error) {
	row := q.db.QueryRow(ctx, getInstallationByGithubID, githubInstallationID)
	var i GithubInstallation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.GithubInstallationID,
		&i.GithubAccountLogin,
		&i.GithubAccountID,
		&i.GithubAccountType,
		&i.RepositorySelection,
		&i.SuspendedAt,
		&i.InstalledByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.State,
	)
	return i, err
}

const getInstallationByOrgID = `-- name: GetInstallationByOrgID :one
SELECT id, organization_id, github_installation_id, github_account_login, github_account_id, github_account_type, repository_selection, suspended_at, installed_by_user_id, created_at, updated_at, state
FROM github_installations
WHERE organization_id = $1
`

func (q *Queries) GetInstallationByOrgID(ctx context.Context, organizationID int64) (GithubInstallation, error) {
	row := q.db.QueryRow(ctx, getInstallationByOrgID, organizationID)
	var i GithubInstallation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.GithubInstallationID,
		&i.GithubAccountLogin,
		&i.GithubAccountID,
		&i.GithubAccountType,
		&i.RepositorySelection,
		&i.SuspendedAt,
		&i.InstalledByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.State,
	)
	return i, err
}

const listInstallationRepositories = `-- name: ListInstallationRepositories :many
SELECT installation_id, github_repository_id, repository_name, repository_full_name, created_at
FROM github_installation_repositories
WHERE installation_id = $1
ORDER BY repository_full_name
`

func (q *Queries) ListInstallationRepositories(ctx context.Context, installationID int64) ([]GithubInstallationRepository, error) {
	rows, err := q.db.Query(ctx, listInstallationRepositories, installationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GithubInstallationRepository
	for rows.Next() {
		var i GithubInstallationRepository
		if err := rows.Scan(
			&i.InstallationID,
			&i.GithubRepositoryID,
			&i.RepositoryName,
			&i.RepositoryFullName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeInstallationRepository = `-- name: RemoveInstallationRepository :exec
DELETE FROM github_installation_repositories
WHERE installation_id = $1
    AND github_repository_id = $2
`

type RemoveInstallationRepositoryParams struct {
	InstallationID     int64
	GithubRepositoryID int64
}

func (q *Queries) RemoveInstallationRepository(ctx context.Context, arg RemoveInstallationRepositoryParams) error {
	_, err := q.db.Exec(ctx, removeInstallationRepository, arg.InstallationID, arg.GithubRepositoryID)
	return err
}

const setInstallationSuspendedByGithubID = `-- name: SetInstallationSuspendedByGithubID :exec
UPDATE github_installations
SET suspended_at = $2,
    updated_at = now()
WHERE github_installation_id = $1
`

type SetInstallationSuspendedByGithubIDParams struct {
	GithubInstallationID int64
	SuspendedAt          pgtype.Timestamptz
}

func (q *Queries) SetInstallationSuspendedByGithubID(ctx context.Context, arg SetInstallationSuspendedByGithubIDParams) error {
	_, err := q.db.Exec(ctx, setInstallationSuspendedByGithubID, arg.GithubInstallationID, arg.SuspendedAt)
	return err
}

const upsertInstallation = `-- name: UpsertInstallation :one
INSERT INTO github_installations (
        organization_id,
        github_installation_id,
        github_account_login,
        github_account_id,
        github_account_type,
        repository_selection,
        suspended_at,
        installed_by_user_id,
        state
    )
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) ON CONFLICT (organization_id) DO
UPDATE
SET github_installation_id = EXCLUDED.github_installation_id,
    github_account_login = EXCLUDED.github_account_login,
    github_account_id = EXCLUDED.github_account_id,
    github_account_type = EXCLUDED.github_account_type,
    repository_selection = EXCLUDED.repository_selection,
    suspended_at = EXCLUDED.suspended_at,
    installed_by_user_id = EXCLUDED.installed_by_user_id,
    state = EXCLUDED.state,
    updated_at = now()
RETURNING id, organization_id, github_installation_id, github_account_login, github_account_id, github_account_type, repository_selection, suspended_at, installed_by_user_id, created_at, updated_at, state
`

type UpsertInstallationParams struct {
	OrganizationID       int64
	GithubInstallationID int64
	GithubAccountLogin   string
	GithubAccountID      int64
	GithubAccountType    string
	RepositorySelection  string
	SuspendedAt          pgtype.Timestamptz
	InstalledByUserID    *int64
	State                GithubInstallationState
}

func (q *Queries) UpsertInstallation(ctx context.Context, arg UpsertInstallationParams) (GithubInstallation, error) {
	row := q.db.QueryRow(ctx, upsertInstallation,
		arg.OrganizationID,
		arg.GithubInstallationID,
		arg.GithubAccountLogin,
		arg.GithubAccountID,
		arg.GithubAccountType,
		arg.RepositorySelection,
		arg.SuspendedAt,
		arg.InstalledByUserID,
		arg.State,
	)
	var i GithubInstallation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.GithubInstallationID,
		&i.GithubAccountLogin,
		&i.GithubAccountID,
		&i.GithubAccountType,
		&i.RepositorySelection,
		&i.SuspendedAt,
		&i.InstalledByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.State,
	)
	return i, err
}
