// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: github_connections.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteGitHubConnection = `-- name: DeleteGitHubConnection :exec
DELETE FROM github_connections
WHERE user_id = $1
`

func (q *Queries) DeleteGitHubConnection(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteGitHubConnection, userID)
	return err
}

const getGitHubConnectionByUserID = `-- name: GetGitHubConnectionByUserID :one
SELECT user_id, access_token_encrypted, refresh_token, token_expires_at, github_user_id, github_login, created_at, updated_at
FROM github_connections
WHERE user_id = $1
`

func (q *Queries) GetGitHubConnectionByUserID(ctx context.Context, userID int64) (GithubConnection, error) {
	row := q.db.QueryRow(ctx, getGitHubConnectionByUserID, userID)
	var i GithubConnection
	err := row.Scan(
		&i.UserID,
		&i.AccessTokenEncrypted,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.GithubUserID,
		&i.GithubLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertGitHubConnection = `-- name: UpsertGitHubConnection :one
INSERT INTO github_connections (user_id, access_token_encrypted, refresh_token, token_expires_at, github_user_id, github_login)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id) DO UPDATE SET
    access_token_encrypted = EXCLUDED.access_token_encrypted,
    refresh_token = EXCLUDED.refresh_token,
    token_expires_at = EXCLUDED.token_expires_at,
    github_user_id = EXCLUDED.github_user_id,
    github_login = EXCLUDED.github_login,
    updated_at = now()
RETURNING user_id, access_token_encrypted, refresh_token, token_expires_at, github_user_id, github_login, created_at, updated_at
`

type UpsertGitHubConnectionParams struct {
	UserID               int64
	AccessTokenEncrypted string
	RefreshToken         *string
	TokenExpiresAt       pgtype.Timestamptz
	GithubUserID         *int64
	GithubLogin          *string
}

func (q *Queries) UpsertGitHubConnection(ctx context.Context, arg UpsertGitHubConnectionParams) (GithubConnection, error) {
	row := q.db.QueryRow(ctx, upsertGitHubConnection,
		arg.UserID,
		arg.AccessTokenEncrypted,
		arg.RefreshToken,
		arg.TokenExpiresAt,
		arg.GithubUserID,
		arg.GithubLogin,
	)
	var i GithubConnection
	err := row.Scan(
		&i.UserID,
		&i.AccessTokenEncrypted,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.GithubUserID,
		&i.GithubLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
