// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: issue_votes.sql

package store

import (
	"context"
)

const incrementIssueVote = `-- name: IncrementIssueVote :one
INSERT INTO issue_votes (owner, repo, issue_number, vote_count)
VALUES ($1, $2, $3, 1)
ON CONFLICT (owner, repo, issue_number) DO UPDATE SET
    vote_count = issue_votes.vote_count + 1,
    updated_at = now()
RETURNING id, owner, repo, issue_number, vote_count, created_at, updated_at
`

type IncrementIssueVoteParams struct {
	Owner       string
	Repo        string
	IssueNumber int32
}

func (q *Queries) IncrementIssueVote(ctx context.Context, arg IncrementIssueVoteParams) (IssueVote, error) {
	row := q.db.QueryRow(ctx, incrementIssueVote, arg.Owner, arg.Repo, arg.IssueNumber)
	var i IssueVote
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Repo,
		&i.IssueNumber,
		&i.VoteCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
