// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/didrikolofsson/github-vote-llm/internal/store (interfaces: Querier)
//
// Generated by this command:
//
//	mockgen -destination=internal/store/mock_querier.go -package=store github.com/didrikolofsson/github-vote-llm/internal/store Querier
//

// Package store is a generated GoMock package.
package store

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// AddFeatureDependency mocks base method.
func (m *MockQuerier) AddFeatureDependency(ctx context.Context, arg AddFeatureDependencyParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFeatureDependency", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddFeatureDependency indicates an expected call of AddFeatureDependency.
func (mr *MockQuerierMockRecorder) AddFeatureDependency(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFeatureDependency", reflect.TypeOf((*MockQuerier)(nil).AddFeatureDependency), ctx, arg)
}

// AddFeatureVote mocks base method.
func (m *MockQuerier) AddFeatureVote(ctx context.Context, arg AddFeatureVoteParams) (FeatureVote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFeatureVote", ctx, arg)
	ret0, _ := ret[0].(FeatureVote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddFeatureVote indicates an expected call of AddFeatureVote.
func (mr *MockQuerierMockRecorder) AddFeatureVote(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFeatureVote", reflect.TypeOf((*MockQuerier)(nil).AddFeatureVote), ctx, arg)
}

// AddOrganizationMember mocks base method.
func (m *MockQuerier) AddOrganizationMember(ctx context.Context, arg AddOrganizationMemberParams) (AddOrganizationMemberRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddOrganizationMember", ctx, arg)
	ret0, _ := ret[0].(AddOrganizationMemberRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddOrganizationMember indicates an expected call of AddOrganizationMember.
func (mr *MockQuerierMockRecorder) AddOrganizationMember(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOrganizationMember", reflect.TypeOf((*MockQuerier)(nil).AddOrganizationMember), ctx, arg)
}

// AddRepository mocks base method.
func (m *MockQuerier) AddRepository(ctx context.Context, arg AddRepositoryParams) (OrganizationRepository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRepository", ctx, arg)
	ret0, _ := ret[0].(OrganizationRepository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddRepository indicates an expected call of AddRepository.
func (mr *MockQuerierMockRecorder) AddRepository(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRepository", reflect.TypeOf((*MockQuerier)(nil).AddRepository), ctx, arg)
}

// CountFeatureVotes mocks base method.
func (m *MockQuerier) CountFeatureVotes(ctx context.Context, featureID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountFeatureVotes", ctx, featureID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountFeatureVotes indicates an expected call of CountFeatureVotes.
func (mr *MockQuerierMockRecorder) CountFeatureVotes(ctx, featureID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountFeatureVotes", reflect.TypeOf((*MockQuerier)(nil).CountFeatureVotes), ctx, featureID)
}

// CreateAuthCode mocks base method.
func (m *MockQuerier) CreateAuthCode(ctx context.Context, arg CreateAuthCodeParams) (UserAuthorizationCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAuthCode", ctx, arg)
	ret0, _ := ret[0].(UserAuthorizationCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAuthCode indicates an expected call of CreateAuthCode.
func (mr *MockQuerierMockRecorder) CreateAuthCode(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAuthCode", reflect.TypeOf((*MockQuerier)(nil).CreateAuthCode), ctx, arg)
}

// CreateFeature mocks base method.
func (m *MockQuerier) CreateFeature(ctx context.Context, arg CreateFeatureParams) (Feature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFeature", ctx, arg)
	ret0, _ := ret[0].(Feature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFeature indicates an expected call of CreateFeature.
func (mr *MockQuerierMockRecorder) CreateFeature(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFeature", reflect.TypeOf((*MockQuerier)(nil).CreateFeature), ctx, arg)
}

// CreateFeatureComment mocks base method.
func (m *MockQuerier) CreateFeatureComment(ctx context.Context, arg CreateFeatureCommentParams) (FeatureComment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFeatureComment", ctx, arg)
	ret0, _ := ret[0].(FeatureComment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFeatureComment indicates an expected call of CreateFeatureComment.
func (mr *MockQuerierMockRecorder) CreateFeatureComment(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFeatureComment", reflect.TypeOf((*MockQuerier)(nil).CreateFeatureComment), ctx, arg)
}

// CreateOrganization mocks base method.
func (m *MockQuerier) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (CreateOrganizationRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrganization", ctx, arg)
	ret0, _ := ret[0].(CreateOrganizationRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrganization indicates an expected call of CreateOrganization.
func (mr *MockQuerierMockRecorder) CreateOrganization(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrganization", reflect.TypeOf((*MockQuerier)(nil).CreateOrganization), ctx, arg)
}

// CreateRefreshToken mocks base method.
func (m *MockQuerier) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (UserRefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRefreshToken", ctx, arg)
	ret0, _ := ret[0].(UserRefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRefreshToken indicates an expected call of CreateRefreshToken.
func (mr *MockQuerierMockRecorder) CreateRefreshToken(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRefreshToken", reflect.TypeOf((*MockQuerier)(nil).CreateRefreshToken), ctx, arg)
}

// CreateRun mocks base method.
func (m *MockQuerier) CreateRun(ctx context.Context, arg CreateRunParams) (FeatureRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRun", ctx, arg)
	ret0, _ := ret[0].(FeatureRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRun indicates an expected call of CreateRun.
func (mr *MockQuerierMockRecorder) CreateRun(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRun", reflect.TypeOf((*MockQuerier)(nil).CreateRun), ctx, arg)
}

// CreateUser mocks base method.
func (m *MockQuerier) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, arg)
	ret0, _ := ret[0].(CreateUserRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockQuerierMockRecorder) CreateUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockQuerier)(nil).CreateUser), ctx, arg)
}

// DeleteCancelledRun mocks base method.
func (m *MockQuerier) DeleteCancelledRun(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCancelledRun", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCancelledRun indicates an expected call of DeleteCancelledRun.
func (mr *MockQuerierMockRecorder) DeleteCancelledRun(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCancelledRun", reflect.TypeOf((*MockQuerier)(nil).DeleteCancelledRun), ctx, id)
}

// DeleteFeature mocks base method.
func (m *MockQuerier) DeleteFeature(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFeature", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFeature indicates an expected call of DeleteFeature.
func (mr *MockQuerierMockRecorder) DeleteFeature(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFeature", reflect.TypeOf((*MockQuerier)(nil).DeleteFeature), ctx, id)
}

// DeleteInstallationByID mocks base method.
func (m *MockQuerier) DeleteInstallationByID(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInstallationByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInstallationByID indicates an expected call of DeleteInstallationByID.
func (mr *MockQuerierMockRecorder) DeleteInstallationByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInstallationByID", reflect.TypeOf((*MockQuerier)(nil).DeleteInstallationByID), ctx, id)
}

// DeleteInstallationByInstallationID mocks base method.
func (m *MockQuerier) DeleteInstallationByInstallationID(ctx context.Context, githubInstallationID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInstallationByInstallationID", ctx, githubInstallationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInstallationByInstallationID indicates an expected call of DeleteInstallationByInstallationID.
func (mr *MockQuerierMockRecorder) DeleteInstallationByInstallationID(ctx, githubInstallationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInstallationByInstallationID", reflect.TypeOf((*MockQuerier)(nil).DeleteInstallationByInstallationID), ctx, githubInstallationID)
}

// DeleteInstallationByOrgID mocks base method.
func (m *MockQuerier) DeleteInstallationByOrgID(ctx context.Context, organizationID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInstallationByOrgID", ctx, organizationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInstallationByOrgID indicates an expected call of DeleteInstallationByOrgID.
func (mr *MockQuerierMockRecorder) DeleteInstallationByOrgID(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInstallationByOrgID", reflect.TypeOf((*MockQuerier)(nil).DeleteInstallationByOrgID), ctx, organizationID)
}

// DeleteOrganization mocks base method.
func (m *MockQuerier) DeleteOrganization(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrganization", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrganization indicates an expected call of DeleteOrganization.
func (mr *MockQuerierMockRecorder) DeleteOrganization(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrganization", reflect.TypeOf((*MockQuerier)(nil).DeleteOrganization), ctx, id)
}

// DeleteOrganizationByID mocks base method.
func (m *MockQuerier) DeleteOrganizationByID(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrganizationByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrganizationByID indicates an expected call of DeleteOrganizationByID.
func (mr *MockQuerierMockRecorder) DeleteOrganizationByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrganizationByID", reflect.TypeOf((*MockQuerier)(nil).DeleteOrganizationByID), ctx, id)
}

// DeleteRefreshToken mocks base method.
func (m *MockQuerier) DeleteRefreshToken(ctx context.Context, tokenHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRefreshToken", ctx, tokenHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRefreshToken indicates an expected call of DeleteRefreshToken.
func (mr *MockQuerierMockRecorder) DeleteRefreshToken(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRefreshToken", reflect.TypeOf((*MockQuerier)(nil).DeleteRefreshToken), ctx, tokenHash)
}

// DeleteUser mocks base method.
func (m *MockQuerier) DeleteUser(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockQuerierMockRecorder) DeleteUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockQuerier)(nil).DeleteUser), ctx, id)
}

// GetAuthCode mocks base method.
func (m *MockQuerier) GetAuthCode(ctx context.Context, code string) (UserAuthorizationCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthCode", ctx, code)
	ret0, _ := ret[0].(UserAuthorizationCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthCode indicates an expected call of GetAuthCode.
func (mr *MockQuerierMockRecorder) GetAuthCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthCode", reflect.TypeOf((*MockQuerier)(nil).GetAuthCode), ctx, code)
}

// GetFeature mocks base method.
func (m *MockQuerier) GetFeature(ctx context.Context, id int64) (Feature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeature", ctx, id)
	ret0, _ := ret[0].(Feature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeature indicates an expected call of GetFeature.
func (mr *MockQuerierMockRecorder) GetFeature(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeature", reflect.TypeOf((*MockQuerier)(nil).GetFeature), ctx, id)
}

// GetFeatureVote mocks base method.
func (m *MockQuerier) GetFeatureVote(ctx context.Context, arg GetFeatureVoteParams) (FeatureVote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeatureVote", ctx, arg)
	ret0, _ := ret[0].(FeatureVote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeatureVote indicates an expected call of GetFeatureVote.
func (mr *MockQuerierMockRecorder) GetFeatureVote(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeatureVote", reflect.TypeOf((*MockQuerier)(nil).GetFeatureVote), ctx, arg)
}

// GetInstallationByInstallationID mocks base method.
func (m *MockQuerier) GetInstallationByInstallationID(ctx context.Context, githubInstallationID int64) (GithubInstallation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstallationByInstallationID", ctx, githubInstallationID)
	ret0, _ := ret[0].(GithubInstallation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInstallationByInstallationID indicates an expected call of GetInstallationByInstallationID.
func (mr *MockQuerierMockRecorder) GetInstallationByInstallationID(ctx, githubInstallationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstallationByInstallationID", reflect.TypeOf((*MockQuerier)(nil).GetInstallationByInstallationID), ctx, githubInstallationID)
}

// GetInstallationByOrgID mocks base method.
func (m *MockQuerier) GetInstallationByOrgID(ctx context.Context, organizationID int64) (GetInstallationByOrgIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstallationByOrgID", ctx, organizationID)
	ret0, _ := ret[0].(GetInstallationByOrgIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInstallationByOrgID indicates an expected call of GetInstallationByOrgID.
func (mr *MockQuerierMockRecorder) GetInstallationByOrgID(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstallationByOrgID", reflect.TypeOf((*MockQuerier)(nil).GetInstallationByOrgID), ctx, organizationID)
}

// GetOrganizationByID mocks base method.
func (m *MockQuerier) GetOrganizationByID(ctx context.Context, id int64) (GetOrganizationByIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrganizationByID", ctx, id)
	ret0, _ := ret[0].(GetOrganizationByIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrganizationByID indicates an expected call of GetOrganizationByID.
func (mr *MockQuerierMockRecorder) GetOrganizationByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganizationByID", reflect.TypeOf((*MockQuerier)(nil).GetOrganizationByID), ctx, id)
}

// GetOrganizationBySlug mocks base method.
func (m *MockQuerier) GetOrganizationBySlug(ctx context.Context, slug string) (GetOrganizationBySlugRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrganizationBySlug", ctx, slug)
	ret0, _ := ret[0].(GetOrganizationBySlugRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrganizationBySlug indicates an expected call of GetOrganizationBySlug.
func (mr *MockQuerierMockRecorder) GetOrganizationBySlug(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganizationBySlug", reflect.TypeOf((*MockQuerier)(nil).GetOrganizationBySlug), ctx, slug)
}

// GetOrganizationMembers mocks base method.
func (m *MockQuerier) GetOrganizationMembers(ctx context.Context, organizationID int64) ([]GetOrganizationMembersRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrganizationMembers", ctx, organizationID)
	ret0, _ := ret[0].([]GetOrganizationMembersRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrganizationMembers indicates an expected call of GetOrganizationMembers.
func (mr *MockQuerierMockRecorder) GetOrganizationMembers(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganizationMembers", reflect.TypeOf((*MockQuerier)(nil).GetOrganizationMembers), ctx, organizationID)
}

// GetOrganizationMembersWithUser mocks base method.
func (m *MockQuerier) GetOrganizationMembersWithUser(ctx context.Context, organizationID int64) ([]GetOrganizationMembersWithUserRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrganizationMembersWithUser", ctx, organizationID)
	ret0, _ := ret[0].([]GetOrganizationMembersWithUserRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrganizationMembersWithUser indicates an expected call of GetOrganizationMembersWithUser.
func (mr *MockQuerierMockRecorder) GetOrganizationMembersWithUser(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganizationMembersWithUser", reflect.TypeOf((*MockQuerier)(nil).GetOrganizationMembersWithUser), ctx, organizationID)
}

// GetOrganizationMembershipByUserID mocks base method.
func (m *MockQuerier) GetOrganizationMembershipByUserID(ctx context.Context, userID int64) (GetOrganizationMembershipByUserIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrganizationMembershipByUserID", ctx, userID)
	ret0, _ := ret[0].(GetOrganizationMembershipByUserIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrganizationMembershipByUserID indicates an expected call of GetOrganizationMembershipByUserID.
func (mr *MockQuerierMockRecorder) GetOrganizationMembershipByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganizationMembershipByUserID", reflect.TypeOf((*MockQuerier)(nil).GetOrganizationMembershipByUserID), ctx, userID)
}

// GetPublicRepositoryByOrgAndName mocks base method.
func (m *MockQuerier) GetPublicRepositoryByOrgAndName(ctx context.Context, arg GetPublicRepositoryByOrgAndNameParams) (OrganizationRepository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicRepositoryByOrgAndName", ctx, arg)
	ret0, _ := ret[0].(OrganizationRepository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicRepositoryByOrgAndName indicates an expected call of GetPublicRepositoryByOrgAndName.
func (mr *MockQuerierMockRecorder) GetPublicRepositoryByOrgAndName(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicRepositoryByOrgAndName", reflect.TypeOf((*MockQuerier)(nil).GetPublicRepositoryByOrgAndName), ctx, arg)
}

// GetRefreshToken mocks base method.
func (m *MockQuerier) GetRefreshToken(ctx context.Context, tokenHash string) (UserRefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshToken", ctx, tokenHash)
	ret0, _ := ret[0].(UserRefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefreshToken indicates an expected call of GetRefreshToken.
func (mr *MockQuerierMockRecorder) GetRefreshToken(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshToken", reflect.TypeOf((*MockQuerier)(nil).GetRefreshToken), ctx, tokenHash)
}

// GetRepository mocks base method.
func (m *MockQuerier) GetRepository(ctx context.Context, id int64) (OrganizationRepository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepository", ctx, id)
	ret0, _ := ret[0].(OrganizationRepository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepository indicates an expected call of GetRepository.
func (mr *MockQuerierMockRecorder) GetRepository(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepository", reflect.TypeOf((*MockQuerier)(nil).GetRepository), ctx, id)
}

// GetRepositoryByFeatureID mocks base method.
func (m *MockQuerier) GetRepositoryByFeatureID(ctx context.Context, id int64) (OrganizationRepository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepositoryByFeatureID", ctx, id)
	ret0, _ := ret[0].(OrganizationRepository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepositoryByFeatureID indicates an expected call of GetRepositoryByFeatureID.
func (mr *MockQuerierMockRecorder) GetRepositoryByFeatureID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepositoryByFeatureID", reflect.TypeOf((*MockQuerier)(nil).GetRepositoryByFeatureID), ctx, id)
}

// GetRepositoryByOwnerAndName mocks base method.
func (m *MockQuerier) GetRepositoryByOwnerAndName(ctx context.Context, arg GetRepositoryByOwnerAndNameParams) (OrganizationRepository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepositoryByOwnerAndName", ctx, arg)
	ret0, _ := ret[0].(OrganizationRepository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepositoryByOwnerAndName indicates an expected call of GetRepositoryByOwnerAndName.
func (mr *MockQuerierMockRecorder) GetRepositoryByOwnerAndName(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepositoryByOwnerAndName", reflect.TypeOf((*MockQuerier)(nil).GetRepositoryByOwnerAndName), ctx, arg)
}

// GetRepositoryFeatureCount mocks base method.
func (m *MockQuerier) GetRepositoryFeatureCount(ctx context.Context, repositoryID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepositoryFeatureCount", ctx, repositoryID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepositoryFeatureCount indicates an expected call of GetRepositoryFeatureCount.
func (mr *MockQuerierMockRecorder) GetRepositoryFeatureCount(ctx, repositoryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepositoryFeatureCount", reflect.TypeOf((*MockQuerier)(nil).GetRepositoryFeatureCount), ctx, repositoryID)
}

// GetRunByID mocks base method.
func (m *MockQuerier) GetRunByID(ctx context.Context, id int64) (GetRunByIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRunByID", ctx, id)
	ret0, _ := ret[0].(GetRunByIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRunByID indicates an expected call of GetRunByID.
func (mr *MockQuerierMockRecorder) GetRunByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRunByID", reflect.TypeOf((*MockQuerier)(nil).GetRunByID), ctx, id)
}

// GetUserByEmail mocks base method.
func (m *MockQuerier) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(GetUserByEmailRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockQuerierMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockQuerier)(nil).GetUserByEmail), ctx, email)
}

// GetUserByEmailWithPassword mocks base method.
func (m *MockQuerier) GetUserByEmailWithPassword(ctx context.Context, email string) (GetUserByEmailWithPasswordRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmailWithPassword", ctx, email)
	ret0, _ := ret[0].(GetUserByEmailWithPasswordRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmailWithPassword indicates an expected call of GetUserByEmailWithPassword.
func (mr *MockQuerierMockRecorder) GetUserByEmailWithPassword(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmailWithPassword", reflect.TypeOf((*MockQuerier)(nil).GetUserByEmailWithPassword), ctx, email)
}

// GetUserByID mocks base method.
func (m *MockQuerier) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(GetUserByIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockQuerierMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockQuerier)(nil).GetUserByID), ctx, id)
}

// IsOrgMember mocks base method.
func (m *MockQuerier) IsOrgMember(ctx context.Context, arg IsOrgMemberParams) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsOrgMember", ctx, arg)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsOrgMember indicates an expected call of IsOrgMember.
func (mr *MockQuerierMockRecorder) IsOrgMember(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsOrgMember", reflect.TypeOf((*MockQuerier)(nil).IsOrgMember), ctx, arg)
}

// ListFeatureComments mocks base method.
func (m *MockQuerier) ListFeatureComments(ctx context.Context, featureID int64) ([]FeatureComment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFeatureComments", ctx, featureID)
	ret0, _ := ret[0].([]FeatureComment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFeatureComments indicates an expected call of ListFeatureComments.
func (mr *MockQuerierMockRecorder) ListFeatureComments(ctx, featureID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFeatureComments", reflect.TypeOf((*MockQuerier)(nil).ListFeatureComments), ctx, featureID)
}

// ListFeatureDependencies mocks base method.
func (m *MockQuerier) ListFeatureDependencies(ctx context.Context, featureID int64) ([]FeatureDependency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFeatureDependencies", ctx, featureID)
	ret0, _ := ret[0].([]FeatureDependency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFeatureDependencies indicates an expected call of ListFeatureDependencies.
func (mr *MockQuerierMockRecorder) ListFeatureDependencies(ctx, featureID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFeatureDependencies", reflect.TypeOf((*MockQuerier)(nil).ListFeatureDependencies), ctx, featureID)
}

// ListFeatureDependenciesForRepository mocks base method.
func (m *MockQuerier) ListFeatureDependenciesForRepository(ctx context.Context, repositoryID int64) ([]FeatureDependency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFeatureDependenciesForRepository", ctx, repositoryID)
	ret0, _ := ret[0].([]FeatureDependency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFeatureDependenciesForRepository indicates an expected call of ListFeatureDependenciesForRepository.
func (mr *MockQuerierMockRecorder) ListFeatureDependenciesForRepository(ctx, repositoryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFeatureDependenciesForRepository", reflect.TypeOf((*MockQuerier)(nil).ListFeatureDependenciesForRepository), ctx, repositoryID)
}

// ListFeatureVotesWithSignals mocks base method.
func (m *MockQuerier) ListFeatureVotesWithSignals(ctx context.Context, featureID int64) ([]ListFeatureVotesWithSignalsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFeatureVotesWithSignals", ctx, featureID)
	ret0, _ := ret[0].([]ListFeatureVotesWithSignalsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFeatureVotesWithSignals indicates an expected call of ListFeatureVotesWithSignals.
func (mr *MockQuerierMockRecorder) ListFeatureVotesWithSignals(ctx, featureID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFeatureVotesWithSignals", reflect.TypeOf((*MockQuerier)(nil).ListFeatureVotesWithSignals), ctx, featureID)
}

// ListFeatures mocks base method.
func (m *MockQuerier) ListFeatures(ctx context.Context, repositoryID int64) ([]Feature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFeatures", ctx, repositoryID)
	ret0, _ := ret[0].([]Feature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFeatures indicates an expected call of ListFeatures.
func (mr *MockQuerierMockRecorder) ListFeatures(ctx, repositoryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFeatures", reflect.TypeOf((*MockQuerier)(nil).ListFeatures), ctx, repositoryID)
}

// ListFeaturesForPortal mocks base method.
func (m *MockQuerier) ListFeaturesForPortal(ctx context.Context, repositoryID int64) ([]ListFeaturesForPortalRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFeaturesForPortal", ctx, repositoryID)
	ret0, _ := ret[0].([]ListFeaturesForPortalRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFeaturesForPortal indicates an expected call of ListFeaturesForPortal.
func (mr *MockQuerierMockRecorder) ListFeaturesForPortal(ctx, repositoryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFeaturesForPortal", reflect.TypeOf((*MockQuerier)(nil).ListFeaturesForPortal), ctx, repositoryID)
}

// ListOrganizationsForUser mocks base method.
func (m *MockQuerier) ListOrganizationsForUser(ctx context.Context, userID int64) ([]ListOrganizationsForUserRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrganizationsForUser", ctx, userID)
	ret0, _ := ret[0].([]ListOrganizationsForUserRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrganizationsForUser indicates an expected call of ListOrganizationsForUser.
func (mr *MockQuerierMockRecorder) ListOrganizationsForUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrganizationsForUser", reflect.TypeOf((*MockQuerier)(nil).ListOrganizationsForUser), ctx, userID)
}

// ListRepositoriesForOrganization mocks base method.
func (m *MockQuerier) ListRepositoriesForOrganization(ctx context.Context, organizationID int64) ([]OrganizationRepository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRepositoriesForOrganization", ctx, organizationID)
	ret0, _ := ret[0].([]OrganizationRepository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRepositoriesForOrganization indicates an expected call of ListRepositoriesForOrganization.
func (mr *MockQuerierMockRecorder) ListRepositoriesForOrganization(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRepositoriesForOrganization", reflect.TypeOf((*MockQuerier)(nil).ListRepositoriesForOrganization), ctx, organizationID)
}

// ListRunsByRepository mocks base method.
func (m *MockQuerier) ListRunsByRepository(ctx context.Context, repositoryID int64) ([]ListRunsByRepositoryRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRunsByRepository", ctx, repositoryID)
	ret0, _ := ret[0].([]ListRunsByRepositoryRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRunsByRepository indicates an expected call of ListRunsByRepository.
func (mr *MockQuerierMockRecorder) ListRunsByRepository(ctx, repositoryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRunsByRepository", reflect.TypeOf((*MockQuerier)(nil).ListRunsByRepository), ctx, repositoryID)
}

// PatchFeature mocks base method.
func (m *MockQuerier) PatchFeature(ctx context.Context, arg PatchFeatureParams) (Feature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchFeature", ctx, arg)
	ret0, _ := ret[0].(Feature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PatchFeature indicates an expected call of PatchFeature.
func (mr *MockQuerierMockRecorder) PatchFeature(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchFeature", reflect.TypeOf((*MockQuerier)(nil).PatchFeature), ctx, arg)
}

// RemoveFeatureDependency mocks base method.
func (m *MockQuerier) RemoveFeatureDependency(ctx context.Context, arg RemoveFeatureDependencyParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFeatureDependency", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFeatureDependency indicates an expected call of RemoveFeatureDependency.
func (mr *MockQuerierMockRecorder) RemoveFeatureDependency(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFeatureDependency", reflect.TypeOf((*MockQuerier)(nil).RemoveFeatureDependency), ctx, arg)
}

// RemoveFeatureVote mocks base method.
func (m *MockQuerier) RemoveFeatureVote(ctx context.Context, arg RemoveFeatureVoteParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFeatureVote", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFeatureVote indicates an expected call of RemoveFeatureVote.
func (mr *MockQuerierMockRecorder) RemoveFeatureVote(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFeatureVote", reflect.TypeOf((*MockQuerier)(nil).RemoveFeatureVote), ctx, arg)
}

// RemoveOrganizationMember mocks base method.
func (m *MockQuerier) RemoveOrganizationMember(ctx context.Context, arg RemoveOrganizationMemberParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveOrganizationMember", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveOrganizationMember indicates an expected call of RemoveOrganizationMember.
func (mr *MockQuerierMockRecorder) RemoveOrganizationMember(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveOrganizationMember", reflect.TypeOf((*MockQuerier)(nil).RemoveOrganizationMember), ctx, arg)
}

// RemoveRepository mocks base method.
func (m *MockQuerier) RemoveRepository(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveRepository", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveRepository indicates an expected call of RemoveRepository.
func (mr *MockQuerierMockRecorder) RemoveRepository(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveRepository", reflect.TypeOf((*MockQuerier)(nil).RemoveRepository), ctx, id)
}

// SetFeatureBuildStatus mocks base method.
func (m *MockQuerier) SetFeatureBuildStatus(ctx context.Context, arg SetFeatureBuildStatusParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFeatureBuildStatus", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetFeatureBuildStatus indicates an expected call of SetFeatureBuildStatus.
func (mr *MockQuerierMockRecorder) SetFeatureBuildStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFeatureBuildStatus", reflect.TypeOf((*MockQuerier)(nil).SetFeatureBuildStatus), ctx, arg)
}

// SetInstallationSuspendedByInstallationID mocks base method.
func (m *MockQuerier) SetInstallationSuspendedByInstallationID(ctx context.Context, arg SetInstallationSuspendedByInstallationIDParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetInstallationSuspendedByInstallationID", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetInstallationSuspendedByInstallationID indicates an expected call of SetInstallationSuspendedByInstallationID.
func (mr *MockQuerierMockRecorder) SetInstallationSuspendedByInstallationID(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetInstallationSuspendedByInstallationID", reflect.TypeOf((*MockQuerier)(nil).SetInstallationSuspendedByInstallationID), ctx, arg)
}

// SetRepositoryPortalPublic mocks base method.
func (m *MockQuerier) SetRepositoryPortalPublic(ctx context.Context, arg SetRepositoryPortalPublicParams) (OrganizationRepository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRepositoryPortalPublic", ctx, arg)
	ret0, _ := ret[0].(OrganizationRepository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetRepositoryPortalPublic indicates an expected call of SetRepositoryPortalPublic.
func (mr *MockQuerierMockRecorder) SetRepositoryPortalPublic(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRepositoryPortalPublic", reflect.TypeOf((*MockQuerier)(nil).SetRepositoryPortalPublic), ctx, arg)
}

// SetRunCancelled mocks base method.
func (m *MockQuerier) SetRunCancelled(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRunCancelled", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRunCancelled indicates an expected call of SetRunCancelled.
func (mr *MockQuerierMockRecorder) SetRunCancelled(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRunCancelled", reflect.TypeOf((*MockQuerier)(nil).SetRunCancelled), ctx, id)
}

// UpdateFeaturePosition mocks base method.
func (m *MockQuerier) UpdateFeaturePosition(ctx context.Context, arg UpdateFeaturePositionParams) (Feature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFeaturePosition", ctx, arg)
	ret0, _ := ret[0].(Feature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateFeaturePosition indicates an expected call of UpdateFeaturePosition.
func (mr *MockQuerierMockRecorder) UpdateFeaturePosition(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFeaturePosition", reflect.TypeOf((*MockQuerier)(nil).UpdateFeaturePosition), ctx, arg)
}

// UpdateOrganizationByID mocks base method.
func (m *MockQuerier) UpdateOrganizationByID(ctx context.Context, arg UpdateOrganizationByIDParams) (UpdateOrganizationByIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrganizationByID", ctx, arg)
	ret0, _ := ret[0].(UpdateOrganizationByIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrganizationByID indicates an expected call of UpdateOrganizationByID.
func (mr *MockQuerierMockRecorder) UpdateOrganizationByID(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrganizationByID", reflect.TypeOf((*MockQuerier)(nil).UpdateOrganizationByID), ctx, arg)
}

// UpdateOrganizationMemberRole mocks base method.
func (m *MockQuerier) UpdateOrganizationMemberRole(ctx context.Context, arg UpdateOrganizationMemberRoleParams) (UpdateOrganizationMemberRoleRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrganizationMemberRole", ctx, arg)
	ret0, _ := ret[0].(UpdateOrganizationMemberRoleRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrganizationMemberRole indicates an expected call of UpdateOrganizationMemberRole.
func (mr *MockQuerierMockRecorder) UpdateOrganizationMemberRole(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrganizationMemberRole", reflect.TypeOf((*MockQuerier)(nil).UpdateOrganizationMemberRole), ctx, arg)
}

// UpdateOrganizationSlug mocks base method.
func (m *MockQuerier) UpdateOrganizationSlug(ctx context.Context, arg UpdateOrganizationSlugParams) (UpdateOrganizationSlugRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrganizationSlug", ctx, arg)
	ret0, _ := ret[0].(UpdateOrganizationSlugRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrganizationSlug indicates an expected call of UpdateOrganizationSlug.
func (mr *MockQuerierMockRecorder) UpdateOrganizationSlug(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrganizationSlug", reflect.TypeOf((*MockQuerier)(nil).UpdateOrganizationSlug), ctx, arg)
}

// UpdateRunPID mocks base method.
func (m *MockQuerier) UpdateRunPID(ctx context.Context, arg UpdateRunPIDParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRunPID", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRunPID indicates an expected call of UpdateRunPID.
func (mr *MockQuerierMockRecorder) UpdateRunPID(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRunPID", reflect.TypeOf((*MockQuerier)(nil).UpdateRunPID), ctx, arg)
}

// UpdateRunPRURL mocks base method.
func (m *MockQuerier) UpdateRunPRURL(ctx context.Context, arg UpdateRunPRURLParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRunPRURL", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRunPRURL indicates an expected call of UpdateRunPRURL.
func (mr *MockQuerierMockRecorder) UpdateRunPRURL(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRunPRURL", reflect.TypeOf((*MockQuerier)(nil).UpdateRunPRURL), ctx, arg)
}

// UpdateRunStatus mocks base method.
func (m *MockQuerier) UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRunStatus", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRunStatus indicates an expected call of UpdateRunStatus.
func (mr *MockQuerierMockRecorder) UpdateRunStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRunStatus", reflect.TypeOf((*MockQuerier)(nil).UpdateRunStatus), ctx, arg)
}

// UpdateUserUsername mocks base method.
func (m *MockQuerier) UpdateUserUsername(ctx context.Context, arg UpdateUserUsernameParams) (UpdateUserUsernameRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserUsername", ctx, arg)
	ret0, _ := ret[0].(UpdateUserUsernameRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserUsername indicates an expected call of UpdateUserUsername.
func (mr *MockQuerierMockRecorder) UpdateUserUsername(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserUsername", reflect.TypeOf((*MockQuerier)(nil).UpdateUserUsername), ctx, arg)
}

// UpsertInstallation mocks base method.
func (m *MockQuerier) UpsertInstallation(ctx context.Context, arg UpsertInstallationParams) (GithubInstallation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertInstallation", ctx, arg)
	ret0, _ := ret[0].(GithubInstallation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertInstallation indicates an expected call of UpsertInstallation.
func (mr *MockQuerierMockRecorder) UpsertInstallation(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertInstallation", reflect.TypeOf((*MockQuerier)(nil).UpsertInstallation), ctx, arg)
}

// UseAuthCode mocks base method.
func (m *MockQuerier) UseAuthCode(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UseAuthCode", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UseAuthCode indicates an expected call of UseAuthCode.
func (mr *MockQuerierMockRecorder) UseAuthCode(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UseAuthCode", reflect.TypeOf((*MockQuerier)(nil).UseAuthCode), ctx, id)
}
