// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthCode = `-- name: CreateAuthCode :one
INSERT INTO authorization_codes (code, user_id, code_challenge, redirect_uri, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, code, user_id, code_challenge, redirect_uri, used, expires_at, created_at
`

type CreateAuthCodeParams struct {
	Code          string
	UserID        int64
	CodeChallenge string
	RedirectUri   string
	ExpiresAt     pgtype.Timestamptz
}

func (q *Queries) CreateAuthCode(ctx context.Context, arg CreateAuthCodeParams) (AuthorizationCode, error) {
	row := q.db.QueryRow(ctx, createAuthCode,
		arg.Code,
		arg.UserID,
		arg.CodeChallenge,
		arg.RedirectUri,
		arg.ExpiresAt,
	)
	var i AuthorizationCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.UserID,
		&i.CodeChallenge,
		&i.RedirectUri,
		&i.Used,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (token_hash, user_id, expires_at)
VALUES ($1, $2, $3)
RETURNING id, token_hash, user_id, expires_at, created_at
`

type CreateRefreshTokenParams struct {
	TokenHash string
	UserID    int64
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :exec
DELETE FROM refresh_tokens
WHERE token_hash = $1
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteRefreshToken, tokenHash)
	return err
}

const getAuthCode = `-- name: GetAuthCode :one
SELECT id, code, user_id, code_challenge, redirect_uri, used, expires_at, created_at
FROM authorization_codes
WHERE code = $1
`

func (q *Queries) GetAuthCode(ctx context.Context, code string) (AuthorizationCode, error) {
	row := q.db.QueryRow(ctx, getAuthCode, code)
	var i AuthorizationCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.UserID,
		&i.CodeChallenge,
		&i.RedirectUri,
		&i.Used,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, token_hash, user_id, expires_at, created_at
FROM refresh_tokens
WHERE token_hash = $1
`

func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const useAuthCode = `-- name: UseAuthCode :exec
UPDATE authorization_codes
SET used = TRUE
WHERE id = $1
`

func (q *Queries) UseAuthCode(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, useAuthCode, id)
	return err
}
