// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organization_repositories.sql

package store

import (
	"context"
)

const addOrganizationRepository = `-- name: AddOrganizationRepository :one
INSERT INTO organization_repositories (organization_id, owner, repo)
VALUES ($1, $2, $3)
RETURNING organization_id, owner, repo, created_at
`

type AddOrganizationRepositoryParams struct {
	OrganizationID int64
	Owner          string
	Repo           string
}

func (q *Queries) AddOrganizationRepository(ctx context.Context, arg AddOrganizationRepositoryParams) (OrganizationRepository, error) {
	row := q.db.QueryRow(ctx, addOrganizationRepository, arg.OrganizationID, arg.Owner, arg.Repo)
	var i OrganizationRepository
	err := row.Scan(
		&i.OrganizationID,
		&i.Owner,
		&i.Repo,
		&i.CreatedAt,
	)
	return i, err
}

const getOrganizationRepository = `-- name: GetOrganizationRepository :one
SELECT organization_id, owner, repo, created_at
FROM organization_repositories
WHERE organization_id = $1 AND owner = $2 AND repo = $3
`

type GetOrganizationRepositoryParams struct {
	OrganizationID int64
	Owner          string
	Repo           string
}

func (q *Queries) GetOrganizationRepository(ctx context.Context, arg GetOrganizationRepositoryParams) (OrganizationRepository, error) {
	row := q.db.QueryRow(ctx, getOrganizationRepository, arg.OrganizationID, arg.Owner, arg.Repo)
	var i OrganizationRepository
	err := row.Scan(
		&i.OrganizationID,
		&i.Owner,
		&i.Repo,
		&i.CreatedAt,
	)
	return i, err
}

const listRepositoriesForOrganization = `-- name: ListRepositoriesForOrganization :many
SELECT organization_id, owner, repo, created_at
FROM organization_repositories
WHERE organization_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListRepositoriesForOrganization(ctx context.Context, organizationID int64) ([]OrganizationRepository, error) {
	rows, err := q.db.Query(ctx, listRepositoriesForOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrganizationRepository
	for rows.Next() {
		var i OrganizationRepository
		if err := rows.Scan(
			&i.OrganizationID,
			&i.Owner,
			&i.Repo,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeOrganizationRepository = `-- name: RemoveOrganizationRepository :exec
DELETE FROM organization_repositories
WHERE organization_id = $1 AND owner = $2 AND repo = $3
`

type RemoveOrganizationRepositoryParams struct {
	OrganizationID int64
	Owner          string
	Repo           string
}

func (q *Queries) RemoveOrganizationRepository(ctx context.Context, arg RemoveOrganizationRepositoryParams) error {
	_, err := q.db.Exec(ctx, removeOrganizationRepository, arg.OrganizationID, arg.Owner, arg.Repo)
	return err
}
