// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organization_repositories.sql

package store

import (
	"context"
)

const addRepository = `-- name: AddRepository :one
INSERT INTO
    organization_repositories (organization_id, owner, name)
VALUES ($1, $2, $3)
RETURNING
    id, organization_id, owner, name, created_at, updated_at, portal_public, description
`

type AddRepositoryParams struct {
	OrganizationID int64
	Owner          string
	Name           string
}

func (q *Queries) AddRepository(ctx context.Context, arg AddRepositoryParams) (OrganizationRepository, error) {
	row := q.db.QueryRow(ctx, addRepository, arg.OrganizationID, arg.Owner, arg.Name)
	var i OrganizationRepository
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Owner,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PortalPublic,
		&i.Description,
	)
	return i, err
}

const getPublicRepositoryByOrgAndName = `-- name: GetPublicRepositoryByOrgAndName :one
SELECT r.id, r.organization_id, r.owner, r.name, r.created_at, r.updated_at, r.portal_public, r.description
FROM
    organization_repositories r
    JOIN organizations o ON o.id = r.organization_id
WHERE
    o.slug = $1
    AND r.name = $2
    AND r.portal_public = true
`

type GetPublicRepositoryByOrgAndNameParams struct {
	Slug string
	Name string
}

func (q *Queries) GetPublicRepositoryByOrgAndName(ctx context.Context, arg GetPublicRepositoryByOrgAndNameParams) (OrganizationRepository, error) {
	row := q.db.QueryRow(ctx, getPublicRepositoryByOrgAndName, arg.Slug, arg.Name)
	var i OrganizationRepository
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Owner,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PortalPublic,
		&i.Description,
	)
	return i, err
}

const getRepository = `-- name: GetRepository :one
SELECT id, organization_id, owner, name, created_at, updated_at, portal_public, description FROM organization_repositories WHERE id = $1
`

func (q *Queries) GetRepository(ctx context.Context, id int64) (OrganizationRepository, error) {
	row := q.db.QueryRow(ctx, getRepository, id)
	var i OrganizationRepository
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Owner,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PortalPublic,
		&i.Description,
	)
	return i, err
}

const getRepositoryByFeatureID = `-- name: GetRepositoryByFeatureID :one
SELECT r.id, r.organization_id, r.owner, r.name, r.created_at, r.updated_at, r.portal_public, r.description
FROM
    organization_repositories r
    JOIN features f ON f.repository_id = r.id
WHERE
    f.id = $1
`

func (q *Queries) GetRepositoryByFeatureID(ctx context.Context, id int64) (OrganizationRepository, error) {
	row := q.db.QueryRow(ctx, getRepositoryByFeatureID, id)
	var i OrganizationRepository
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Owner,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PortalPublic,
		&i.Description,
	)
	return i, err
}

const getRepositoryByOwnerAndName = `-- name: GetRepositoryByOwnerAndName :one
SELECT id, organization_id, owner, name, created_at, updated_at, portal_public, description
FROM organization_repositories
WHERE
    organization_id = $1
    AND owner = $2
    AND name = $3
`

type GetRepositoryByOwnerAndNameParams struct {
	OrganizationID int64
	Owner          string
	Name           string
}

func (q *Queries) GetRepositoryByOwnerAndName(ctx context.Context, arg GetRepositoryByOwnerAndNameParams) (OrganizationRepository, error) {
	row := q.db.QueryRow(ctx, getRepositoryByOwnerAndName, arg.OrganizationID, arg.Owner, arg.Name)
	var i OrganizationRepository
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Owner,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PortalPublic,
		&i.Description,
	)
	return i, err
}

const getRepositoryFeatureCount = `-- name: GetRepositoryFeatureCount :one
SELECT COUNT(*) AS count FROM features WHERE repository_id = $1
`

func (q *Queries) GetRepositoryFeatureCount(ctx context.Context, repositoryID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getRepositoryFeatureCount, repositoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listRepositoriesForOrganization = `-- name: ListRepositoriesForOrganization :many
SELECT id, organization_id, owner, name, created_at, updated_at, portal_public, description
FROM organization_repositories
WHERE
    organization_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListRepositoriesForOrganization(ctx context.Context, organizationID int64) ([]OrganizationRepository, error) {
	rows, err := q.db.Query(ctx, listRepositoriesForOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrganizationRepository
	for rows.Next() {
		var i OrganizationRepository
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Owner,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PortalPublic,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRepository = `-- name: RemoveRepository :exec
DELETE FROM organization_repositories WHERE id = $1
`

func (q *Queries) RemoveRepository(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, removeRepository, id)
	return err
}

const setRepositoryPortalPublic = `-- name: SetRepositoryPortalPublic :one
UPDATE organization_repositories
SET
    portal_public = $2,
    updated_at = now()
WHERE
    id = $1
RETURNING
    id, organization_id, owner, name, created_at, updated_at, portal_public, description
`

type SetRepositoryPortalPublicParams struct {
	ID           int64
	PortalPublic bool
}

func (q *Queries) SetRepositoryPortalPublic(ctx context.Context, arg SetRepositoryPortalPublicParams) (OrganizationRepository, error) {
	row := q.db.QueryRow(ctx, setRepositoryPortalPublic, arg.ID, arg.PortalPublic)
	var i OrganizationRepository
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Owner,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PortalPublic,
		&i.Description,
	)
	return i, err
}
