// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organization_github_installations.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteInstallationByID = `-- name: DeleteInstallationByID :exec
DELETE FROM github_installations WHERE id = $1
`

func (q *Queries) DeleteInstallationByID(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteInstallationByID, id)
	return err
}

const deleteInstallationByInstallationID = `-- name: DeleteInstallationByInstallationID :exec
DELETE FROM github_installations WHERE github_installation_id = $1
`

func (q *Queries) DeleteInstallationByInstallationID(ctx context.Context, githubInstallationID int64) error {
	_, err := q.db.Exec(ctx, deleteInstallationByInstallationID, githubInstallationID)
	return err
}

const deleteInstallationByOrgID = `-- name: DeleteInstallationByOrgID :exec
DELETE FROM github_installations WHERE organization_id = $1
`

func (q *Queries) DeleteInstallationByOrgID(ctx context.Context, organizationID int64) error {
	_, err := q.db.Exec(ctx, deleteInstallationByOrgID, organizationID)
	return err
}

const getInstallationByInstallationID = `-- name: GetInstallationByInstallationID :one
SELECT id, organization_id, github_installation_id, github_account_login, github_account_id, github_account_type, repository_selection, suspended_at, installed_by_user_id, created_at, updated_at FROM github_installations WHERE github_installation_id = $1
`

func (q *Queries) GetInstallationByInstallationID(ctx context.Context, githubInstallationID int64) (GithubInstallation, error) {
	row := q.db.QueryRow(ctx, getInstallationByInstallationID, githubInstallationID)
	var i GithubInstallation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.GithubInstallationID,
		&i.GithubAccountLogin,
		&i.GithubAccountID,
		&i.GithubAccountType,
		&i.RepositorySelection,
		&i.SuspendedAt,
		&i.InstalledByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstallationByOrgID = `-- name: GetInstallationByOrgID :one
SELECT gi.id, gi.organization_id, gi.github_installation_id, gi.github_account_login, gi.github_account_id, gi.github_account_type, gi.repository_selection, gi.suspended_at, gi.installed_by_user_id, gi.created_at, gi.updated_at, u.username AS installed_by_user_name
FROM
    github_installations gi
    INNER JOIN users u ON gi.installed_by_user_id = u.id
WHERE
    gi.organization_id = $1
`

type GetInstallationByOrgIDRow struct {
	ID                   int64
	OrganizationID       int64
	GithubInstallationID int64
	GithubAccountLogin   string
	GithubAccountID      int64
	GithubAccountType    string
	RepositorySelection  string
	SuspendedAt          pgtype.Timestamptz
	InstalledByUserID    *int64
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	InstalledByUserName  *string
}

func (q *Queries) GetInstallationByOrgID(ctx context.Context, organizationID int64) (GetInstallationByOrgIDRow, error) {
	row := q.db.QueryRow(ctx, getInstallationByOrgID, organizationID)
	var i GetInstallationByOrgIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.GithubInstallationID,
		&i.GithubAccountLogin,
		&i.GithubAccountID,
		&i.GithubAccountType,
		&i.RepositorySelection,
		&i.SuspendedAt,
		&i.InstalledByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InstalledByUserName,
	)
	return i, err
}

const setInstallationSuspendedByInstallationID = `-- name: SetInstallationSuspendedByInstallationID :exec
UPDATE github_installations
SET
    suspended_at = $2,
    updated_at = now()
WHERE
    github_installation_id = $1
`

type SetInstallationSuspendedByInstallationIDParams struct {
	GithubInstallationID int64
	SuspendedAt          pgtype.Timestamptz
}

func (q *Queries) SetInstallationSuspendedByInstallationID(ctx context.Context, arg SetInstallationSuspendedByInstallationIDParams) error {
	_, err := q.db.Exec(ctx, setInstallationSuspendedByInstallationID, arg.GithubInstallationID, arg.SuspendedAt)
	return err
}

const upsertInstallation = `-- name: UpsertInstallation :one
INSERT INTO
    github_installations (
        organization_id,
        github_installation_id,
        github_account_login,
        github_account_id,
        github_account_type,
        repository_selection,
        suspended_at,
        installed_by_user_id
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8
    )
ON CONFLICT (organization_id) DO
UPDATE
SET
    github_installation_id = EXCLUDED.github_installation_id,
    github_account_login = EXCLUDED.github_account_login,
    github_account_id = EXCLUDED.github_account_id,
    github_account_type = EXCLUDED.github_account_type,
    repository_selection = EXCLUDED.repository_selection,
    suspended_at = EXCLUDED.suspended_at,
    installed_by_user_id = EXCLUDED.installed_by_user_id,
    updated_at = now()
RETURNING
    id, organization_id, github_installation_id, github_account_login, github_account_id, github_account_type, repository_selection, suspended_at, installed_by_user_id, created_at, updated_at
`

type UpsertInstallationParams struct {
	OrganizationID       int64
	GithubInstallationID int64
	GithubAccountLogin   string
	GithubAccountID      int64
	GithubAccountType    string
	RepositorySelection  string
	SuspendedAt          pgtype.Timestamptz
	InstalledByUserID    *int64
}

func (q *Queries) UpsertInstallation(ctx context.Context, arg UpsertInstallationParams) (GithubInstallation, error) {
	row := q.db.QueryRow(ctx, upsertInstallation,
		arg.OrganizationID,
		arg.GithubInstallationID,
		arg.GithubAccountLogin,
		arg.GithubAccountID,
		arg.GithubAccountType,
		arg.RepositorySelection,
		arg.SuspendedAt,
		arg.InstalledByUserID,
	)
	var i GithubInstallation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.GithubInstallationID,
		&i.GithubAccountLogin,
		&i.GithubAccountID,
		&i.GithubAccountType,
		&i.RepositorySelection,
		&i.SuspendedAt,
		&i.InstalledByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
