// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: proposals.sql

package store

import (
	"context"
)

const createProposal = `-- name: CreateProposal :one
INSERT INTO proposals (owner, repo, title, description) VALUES ($1, $2, $3, $4) RETURNING id, owner, repo, title, description, vote_count, status, created_at, updated_at
`

type CreateProposalParams struct {
	Owner       string
	Repo        string
	Title       string
	Description string
}

func (q *Queries) CreateProposal(ctx context.Context, arg CreateProposalParams) (Proposal, error) {
	row := q.db.QueryRow(ctx, createProposal,
		arg.Owner,
		arg.Repo,
		arg.Title,
		arg.Description,
	)
	var i Proposal
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Repo,
		&i.Title,
		&i.Description,
		&i.VoteCount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProposal = `-- name: GetProposal :one
SELECT id, owner, repo, title, description, vote_count, status, created_at, updated_at FROM proposals WHERE id = $1
`

func (q *Queries) GetProposal(ctx context.Context, id int64) (Proposal, error) {
	row := q.db.QueryRow(ctx, getProposal, id)
	var i Proposal
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Repo,
		&i.Title,
		&i.Description,
		&i.VoteCount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementProposalVote = `-- name: IncrementProposalVote :one
UPDATE proposals SET vote_count = vote_count + 1, updated_at = NOW()
WHERE id = $1 RETURNING id, owner, repo, title, description, vote_count, status, created_at, updated_at
`

func (q *Queries) IncrementProposalVote(ctx context.Context, id int64) (Proposal, error) {
	row := q.db.QueryRow(ctx, incrementProposalVote, id)
	var i Proposal
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Repo,
		&i.Title,
		&i.Description,
		&i.VoteCount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProposals = `-- name: ListProposals :many
SELECT id, owner, repo, title, description, vote_count, status, created_at, updated_at FROM proposals WHERE owner = $1 AND repo = $2 ORDER BY vote_count DESC
`

type ListProposalsParams struct {
	Owner string
	Repo  string
}

func (q *Queries) ListProposals(ctx context.Context, arg ListProposalsParams) ([]Proposal, error) {
	rows, err := q.db.Query(ctx, listProposals, arg.Owner, arg.Repo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Proposal
	for rows.Next() {
		var i Proposal
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Repo,
			&i.Title,
			&i.Description,
			&i.VoteCount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProposalStatus = `-- name: UpdateProposalStatus :one
UPDATE proposals SET status = $2, updated_at = NOW() WHERE id = $1 RETURNING id, owner, repo, title, description, vote_count, status, created_at, updated_at
`

type UpdateProposalStatusParams struct {
	ID     int64
	Status string
}

func (q *Queries) UpdateProposalStatus(ctx context.Context, arg UpdateProposalStatusParams) (Proposal, error) {
	row := q.db.QueryRow(ctx, updateProposalStatus, arg.ID, arg.Status)
	var i Proposal
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Repo,
		&i.Title,
		&i.Description,
		&i.VoteCount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
