// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: proposal_comments.sql

package store

import (
	"context"
)

const createProposalComment = `-- name: CreateProposalComment :one
INSERT INTO proposal_comments (proposal_id, body, author_name) VALUES ($1, $2, $3) RETURNING id, proposal_id, body, author_name, created_at
`

type CreateProposalCommentParams struct {
	ProposalID int64
	Body       string
	AuthorName string
}

func (q *Queries) CreateProposalComment(ctx context.Context, arg CreateProposalCommentParams) (ProposalComment, error) {
	row := q.db.QueryRow(ctx, createProposalComment, arg.ProposalID, arg.Body, arg.AuthorName)
	var i ProposalComment
	err := row.Scan(
		&i.ID,
		&i.ProposalID,
		&i.Body,
		&i.AuthorName,
		&i.CreatedAt,
	)
	return i, err
}

const listProposalComments = `-- name: ListProposalComments :many
SELECT id, proposal_id, body, author_name, created_at FROM proposal_comments WHERE proposal_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListProposalComments(ctx context.Context, proposalID int64) ([]ProposalComment, error) {
	rows, err := q.db.Query(ctx, listProposalComments, proposalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProposalComment
	for rows.Next() {
		var i ProposalComment
		if err := rows.Scan(
			&i.ID,
			&i.ProposalID,
			&i.Body,
			&i.AuthorName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
