// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"
)

type Querier interface {
	AddFeatureDependency(ctx context.Context, arg AddFeatureDependencyParams) error
	AddFeatureVote(ctx context.Context, arg AddFeatureVoteParams) (FeatureVote, error)
	AddOrganizationMember(ctx context.Context, arg AddOrganizationMemberParams) (AddOrganizationMemberRow, error)
	AddRepository(ctx context.Context, arg AddRepositoryParams) (OrganizationRepository, error)
	CountFeatureVotes(ctx context.Context, featureID int64) (int64, error)
	CreateAuthCode(ctx context.Context, arg CreateAuthCodeParams) (UserAuthorizationCode, error)
	CreateFeature(ctx context.Context, arg CreateFeatureParams) (Feature, error)
	CreateFeatureComment(ctx context.Context, arg CreateFeatureCommentParams) (FeatureComment, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (CreateOrganizationRow, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (UserRefreshToken, error)
	CreateRun(ctx context.Context, arg CreateRunParams) (FeatureRun, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteCancelledRun(ctx context.Context, id int64) error
	DeleteFeature(ctx context.Context, id int64) error
	DeleteInstallationByID(ctx context.Context, id int64) error
	DeleteInstallationByInstallationID(ctx context.Context, githubInstallationID int64) error
	DeleteInstallationByOrgID(ctx context.Context, organizationID int64) error
	DeleteOrganization(ctx context.Context, id int64) error
	DeleteOrganizationByID(ctx context.Context, id int64) error
	DeleteRefreshToken(ctx context.Context, tokenHash string) error
	DeleteUser(ctx context.Context, id int64) error
	GetAuthCode(ctx context.Context, code string) (UserAuthorizationCode, error)
	GetFeature(ctx context.Context, id int64) (Feature, error)
	GetFeatureVote(ctx context.Context, arg GetFeatureVoteParams) (FeatureVote, error)
	GetInstallationByInstallationID(ctx context.Context, githubInstallationID int64) (GithubInstallation, error)
	GetInstallationByOrgID(ctx context.Context, organizationID int64) (GetInstallationByOrgIDRow, error)
	GetOrganizationByID(ctx context.Context, id int64) (GetOrganizationByIDRow, error)
	GetOrganizationBySlug(ctx context.Context, slug string) (GetOrganizationBySlugRow, error)
	GetOrganizationMembers(ctx context.Context, organizationID int64) ([]GetOrganizationMembersRow, error)
	GetOrganizationMembersWithUser(ctx context.Context, organizationID int64) ([]GetOrganizationMembersWithUserRow, error)
	GetOrganizationMembershipByUserID(ctx context.Context, userID int64) (GetOrganizationMembershipByUserIDRow, error)
	GetPublicRepositoryByOrgAndName(ctx context.Context, arg GetPublicRepositoryByOrgAndNameParams) (OrganizationRepository, error)
	GetRefreshToken(ctx context.Context, tokenHash string) (UserRefreshToken, error)
	GetRepository(ctx context.Context, id int64) (OrganizationRepository, error)
	GetRepositoryByFeatureID(ctx context.Context, id int64) (OrganizationRepository, error)
	GetRepositoryByOwnerAndName(ctx context.Context, arg GetRepositoryByOwnerAndNameParams) (OrganizationRepository, error)
	GetRepositoryFeatureCount(ctx context.Context, repositoryID int64) (int64, error)
	GetRunByID(ctx context.Context, id int64) (GetRunByIDRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByEmailWithPassword(ctx context.Context, email string) (GetUserByEmailWithPasswordRow, error)
	GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error)
	IsOrgMember(ctx context.Context, arg IsOrgMemberParams) (bool, error)
	ListFeatureComments(ctx context.Context, featureID int64) ([]FeatureComment, error)
	ListFeatureDependencies(ctx context.Context, featureID int64) ([]FeatureDependency, error)
	ListFeatureDependenciesForRepository(ctx context.Context, repositoryID int64) ([]FeatureDependency, error)
	ListFeatureVotesWithSignals(ctx context.Context, featureID int64) ([]ListFeatureVotesWithSignalsRow, error)
	ListFeatures(ctx context.Context, repositoryID int64) ([]Feature, error)
	ListFeaturesForPortal(ctx context.Context, repositoryID int64) ([]ListFeaturesForPortalRow, error)
	ListOrganizationsForUser(ctx context.Context, userID int64) ([]ListOrganizationsForUserRow, error)
	ListRepositoriesForOrganization(ctx context.Context, organizationID int64) ([]OrganizationRepository, error)
	ListRunsByRepository(ctx context.Context, repositoryID int64) ([]ListRunsByRepositoryRow, error)
	PatchFeature(ctx context.Context, arg PatchFeatureParams) (Feature, error)
	RemoveFeatureDependency(ctx context.Context, arg RemoveFeatureDependencyParams) error
	RemoveFeatureVote(ctx context.Context, arg RemoveFeatureVoteParams) error
	RemoveOrganizationMember(ctx context.Context, arg RemoveOrganizationMemberParams) error
	RemoveRepository(ctx context.Context, id int64) error
	SetFeatureBuildStatus(ctx context.Context, arg SetFeatureBuildStatusParams) error
	SetInstallationSuspendedByInstallationID(ctx context.Context, arg SetInstallationSuspendedByInstallationIDParams) error
	SetRepositoryPortalPublic(ctx context.Context, arg SetRepositoryPortalPublicParams) (OrganizationRepository, error)
	SetRunCancelled(ctx context.Context, id int64) error
	UpdateFeaturePosition(ctx context.Context, arg UpdateFeaturePositionParams) (Feature, error)
	UpdateOrganizationByID(ctx context.Context, arg UpdateOrganizationByIDParams) (UpdateOrganizationByIDRow, error)
	UpdateOrganizationMemberRole(ctx context.Context, arg UpdateOrganizationMemberRoleParams) (UpdateOrganizationMemberRoleRow, error)
	UpdateOrganizationSlug(ctx context.Context, arg UpdateOrganizationSlugParams) (UpdateOrganizationSlugRow, error)
	UpdateRunPID(ctx context.Context, arg UpdateRunPIDParams) error
	UpdateRunPRURL(ctx context.Context, arg UpdateRunPRURLParams) error
	UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) error
	UpdateUserUsername(ctx context.Context, arg UpdateUserUsernameParams) (UpdateUserUsernameRow, error)
	UpsertInstallation(ctx context.Context, arg UpsertInstallationParams) (GithubInstallation, error)
	UseAuthCode(ctx context.Context, id int64) error
}

var _ Querier = (*Queries)(nil)
