// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repositories.sql

package store

import (
	"context"
)

const addRepository = `-- name: AddRepository :one
INSERT INTO repositories (organization_id, owner, name)
VALUES ($1, $2, $3)
RETURNING id, organization_id, owner, name, created_at, updated_at
`

type AddRepositoryParams struct {
	OrganizationID int64
	Owner          string
	Name           string
}

func (q *Queries) AddRepository(ctx context.Context, arg AddRepositoryParams) (Repository, error) {
	row := q.db.QueryRow(ctx, addRepository, arg.OrganizationID, arg.Owner, arg.Name)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Owner,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepository = `-- name: GetRepository :one
SELECT id, organization_id, owner, name, created_at, updated_at FROM repositories WHERE id = $1
`

func (q *Queries) GetRepository(ctx context.Context, id int64) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepository, id)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Owner,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepositoryByOwnerAndName = `-- name: GetRepositoryByOwnerAndName :one
SELECT id, organization_id, owner, name, created_at, updated_at FROM repositories
WHERE organization_id = $1 AND owner = $2 AND name = $3
`

type GetRepositoryByOwnerAndNameParams struct {
	OrganizationID int64
	Owner          string
	Name           string
}

func (q *Queries) GetRepositoryByOwnerAndName(ctx context.Context, arg GetRepositoryByOwnerAndNameParams) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepositoryByOwnerAndName, arg.OrganizationID, arg.Owner, arg.Name)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Owner,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRepositoriesForOrganization = `-- name: ListRepositoriesForOrganization :many
SELECT id, organization_id, owner, name, created_at, updated_at FROM repositories
WHERE organization_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListRepositoriesForOrganization(ctx context.Context, organizationID int64) ([]Repository, error) {
	rows, err := q.db.Query(ctx, listRepositoriesForOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repository
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Owner,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRepository = `-- name: RemoveRepository :exec
DELETE FROM repositories WHERE id = $1
`

func (q *Queries) RemoveRepository(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, removeRepository, id)
	return err
}
