// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runs.sql

package store

import (
	"context"
)

const createRun = `-- name: CreateRun :one
INSERT INTO feature_runs (
        prompt,
        feature_id,
        status,
        created_by_user_id
    )
VALUES ($1, $2, $3, $4)
RETURNING id, prompt, feature_id, status, created_by_user_id, created_at, completed_at
`

type CreateRunParams struct {
	Prompt          string
	FeatureID       int64
	Status          FeatureRunStatus
	CreatedByUserID int64
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (FeatureRun, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.Prompt,
		arg.FeatureID,
		arg.Status,
		arg.CreatedByUserID,
	)
	var i FeatureRun
	err := row.Scan(
		&i.ID,
		&i.Prompt,
		&i.FeatureID,
		&i.Status,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}
