// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runs.sql

package store

import (
	"context"
)

const createRun = `-- name: CreateRun :one
INSERT INTO feature_runs (
        prompt,
        feature_id,
        status,
        created_by_user_id
    )
VALUES ($1, $2, $3, $4)
RETURNING id, prompt, feature_id, status, created_by_user_id, created_at, completed_at
`

type CreateRunParams struct {
	Prompt          string
	FeatureID       int64
	Status          FeatureRunStatus
	CreatedByUserID int64
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (FeatureRun, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.Prompt,
		arg.FeatureID,
		arg.Status,
		arg.CreatedByUserID,
	)
	var i FeatureRun
	err := row.Scan(
		&i.ID,
		&i.Prompt,
		&i.FeatureID,
		&i.Status,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getRunByID = `-- name: GetRunByID :one
SELECT id, prompt, feature_id, status, created_by_user_id, created_at, completed_at
FROM feature_runs
WHERE id = $1
`

func (q *Queries) GetRunByID(ctx context.Context, id int64) (FeatureRun, error) {
	row := q.db.QueryRow(ctx, getRunByID, id)
	var i FeatureRun
	err := row.Scan(
		&i.ID,
		&i.Prompt,
		&i.FeatureID,
		&i.Status,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateRunStatus = `-- name: UpdateRunStatus :exec
UPDATE feature_runs
SET status = $1
WHERE id = $2
`

type UpdateRunStatusParams struct {
	Status FeatureRunStatus
	ID     int64
}

func (q *Queries) UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) error {
	_, err := q.db.Exec(ctx, updateRunStatus, arg.Status, arg.ID)
	return err
}
