// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type FeatureStatus string

const (
	FeatureStatusOpen       FeatureStatus = "open"
	FeatureStatusPlanned    FeatureStatus = "planned"
	FeatureStatusInProgress FeatureStatus = "in_progress"
	FeatureStatusDone       FeatureStatus = "done"
	FeatureStatusRejected   FeatureStatus = "rejected"
)

func (e *FeatureStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FeatureStatus(s)
	case string:
		*e = FeatureStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FeatureStatus: %T", src)
	}
	return nil
}

type NullFeatureStatus struct {
	FeatureStatus FeatureStatus
	Valid         bool // Valid is true if FeatureStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFeatureStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FeatureStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FeatureStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFeatureStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FeatureStatus), nil
}

type OrganizationMemberRole string

const (
	OrganizationMemberRoleOwner  OrganizationMemberRole = "owner"
	OrganizationMemberRoleMember OrganizationMemberRole = "member"
)

func (e *OrganizationMemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrganizationMemberRole(s)
	case string:
		*e = OrganizationMemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for OrganizationMemberRole: %T", src)
	}
	return nil
}

type NullOrganizationMemberRole struct {
	OrganizationMemberRole OrganizationMemberRole
	Valid                  bool // Valid is true if OrganizationMemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrganizationMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.OrganizationMemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrganizationMemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrganizationMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrganizationMemberRole), nil
}

type AuthorizationCode struct {
	ID            int64
	Code          string
	UserID        int64
	CodeChallenge string
	RedirectUri   string
	Used          bool
	ExpiresAt     pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

type Feature struct {
	ID            int64
	RepositoryID  int64
	Title         string
	Description   string
	Status        FeatureStatus
	Area          *string
	RoadmapX      *float64
	RoadmapY      *float64
	RoadmapLocked bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type FeatureComment struct {
	ID         int64
	FeatureID  int64
	Body       string
	AuthorName string
	CreatedAt  pgtype.Timestamptz
}

type FeatureDependency struct {
	FeatureID int64
	DependsOn int64
}

type FeatureVote struct {
	ID         int64
	FeatureID  int64
	VoterToken string
	CreatedAt  pgtype.Timestamptz
}

type GithubConnection struct {
	UserID               int64
	AccessTokenEncrypted string
	RefreshToken         *string
	TokenExpiresAt       pgtype.Timestamptz
	GithubUserID         *int64
	GithubLogin          *string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type Organization struct {
	ID        int64
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Slug      string
}

type OrganizationMember struct {
	OrganizationID int64
	UserID         int64
	Role           OrganizationMemberRole
	CreatedAt      pgtype.Timestamptz
}

type RefreshToken struct {
	ID        int64
	TokenHash string
	UserID    int64
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Repository struct {
	ID             int64
	OrganizationID int64
	Owner          string
	Name           string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	PortalPublic   bool
}

type User struct {
	ID        int64
	Email     string
	Password  string
	Username  *string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
