// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_oauth.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthCode = `-- name: CreateAuthCode :one
INSERT INTO
    user_authorization_codes (
        code,
        user_id,
        code_challenge,
        redirect_uri,
        expires_at
    )
VALUES ($1, $2, $3, $4, $5)
RETURNING
    id,
    code,
    user_id,
    code_challenge,
    redirect_uri,
    used,
    expires_at,
    created_at
`

type CreateAuthCodeParams struct {
	Code          string
	UserID        int64
	CodeChallenge string
	RedirectUri   string
	ExpiresAt     pgtype.Timestamptz
}

func (q *Queries) CreateAuthCode(ctx context.Context, arg CreateAuthCodeParams) (UserAuthorizationCode, error) {
	row := q.db.QueryRow(ctx, createAuthCode,
		arg.Code,
		arg.UserID,
		arg.CodeChallenge,
		arg.RedirectUri,
		arg.ExpiresAt,
	)
	var i UserAuthorizationCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.UserID,
		&i.CodeChallenge,
		&i.RedirectUri,
		&i.Used,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO
    user_refresh_tokens (
        token_hash,
        user_id,
        expires_at
    )
VALUES ($1, $2, $3)
RETURNING
    id,
    token_hash,
    user_id,
    expires_at,
    created_at
`

type CreateRefreshTokenParams struct {
	TokenHash string
	UserID    int64
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (UserRefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	var i UserRefreshToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :exec
DELETE FROM user_refresh_tokens WHERE token_hash = $1
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteRefreshToken, tokenHash)
	return err
}

const getAuthCode = `-- name: GetAuthCode :one
SELECT
    id,
    code,
    user_id,
    code_challenge,
    redirect_uri,
    used,
    expires_at,
    created_at
FROM user_authorization_codes
WHERE
    code = $1
`

func (q *Queries) GetAuthCode(ctx context.Context, code string) (UserAuthorizationCode, error) {
	row := q.db.QueryRow(ctx, getAuthCode, code)
	var i UserAuthorizationCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.UserID,
		&i.CodeChallenge,
		&i.RedirectUri,
		&i.Used,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getGithubConnectionByUserID = `-- name: GetGithubConnectionByUserID :one
SELECT id, user_id, access_token, access_token_expires_at, refresh_token, updated_at FROM github_connections WHERE user_id = $1
`

func (q *Queries) GetGithubConnectionByUserID(ctx context.Context, userID int64) (GithubConnection, error) {
	row := q.db.QueryRow(ctx, getGithubConnectionByUserID, userID)
	var i GithubConnection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccessToken,
		&i.AccessTokenExpiresAt,
		&i.RefreshToken,
		&i.UpdatedAt,
	)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT
    id,
    token_hash,
    user_id,
    expires_at,
    created_at
FROM user_refresh_tokens
WHERE
    token_hash = $1
`

func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash string) (UserRefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, tokenHash)
	var i UserRefreshToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertGithubAccountTokenByUserID = `-- name: UpsertGithubAccountTokenByUserID :one
INSERT INTO
    github_connections (
        user_id,
        access_token,
        access_token_expires_at,
        refresh_token
    )
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO
UPDATE
SET
    access_token = EXCLUDED.access_token,
    access_token_expires_at = EXCLUDED.access_token_expires_at,
    refresh_token = EXCLUDED.refresh_token,
    updated_at = now()
RETURNING
    user_id,
    access_token,
    access_token_expires_at,
    refresh_token,
    updated_at
`

type UpsertGithubAccountTokenByUserIDParams struct {
	UserID               int64
	AccessToken          string
	AccessTokenExpiresAt pgtype.Timestamptz
	RefreshToken         string
}

type UpsertGithubAccountTokenByUserIDRow struct {
	UserID               int64
	AccessToken          string
	AccessTokenExpiresAt pgtype.Timestamptz
	RefreshToken         string
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) UpsertGithubAccountTokenByUserID(ctx context.Context, arg UpsertGithubAccountTokenByUserIDParams) (UpsertGithubAccountTokenByUserIDRow, error) {
	row := q.db.QueryRow(ctx, upsertGithubAccountTokenByUserID,
		arg.UserID,
		arg.AccessToken,
		arg.AccessTokenExpiresAt,
		arg.RefreshToken,
	)
	var i UpsertGithubAccountTokenByUserIDRow
	err := row.Scan(
		&i.UserID,
		&i.AccessToken,
		&i.AccessTokenExpiresAt,
		&i.RefreshToken,
		&i.UpdatedAt,
	)
	return i, err
}

const useAuthCode = `-- name: UseAuthCode :exec
UPDATE user_authorization_codes SET used = TRUE WHERE id = $1
`

func (q *Queries) UseAuthCode(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, useAuthCode, id)
	return err
}
