// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { GetHealthData, GetHealthResponses, HandleGithubWebhookData, HandleGithubWebhookResponses, HandleGithubWebhookErrors, ListRunsData, ListRunsResponses, ListRunsErrors, CreateRunData, CreateRunResponses, CreateRunErrors, GetRunData, GetRunResponses, GetRunErrors, RetryRunData, RetryRunResponses, RetryRunErrors, CancelRunData, CancelRunResponses, CancelRunErrors, ListReposData, ListReposResponses, ListReposErrors, DeleteRepoConfigData, DeleteRepoConfigResponses, DeleteRepoConfigErrors, GetRepoConfigData, GetRepoConfigResponses, GetRepoConfigErrors, UpdateRepoConfigData, UpdateRepoConfigResponses, UpdateRepoConfigErrors, ListRoadmapItemsData, ListRoadmapItemsResponses, ListRoadmapItemsErrors, UpdateProposalStatusData, UpdateProposalStatusResponses, UpdateProposalStatusErrors, ListBoardProposalsData, ListBoardProposalsResponses, ListBoardProposalsErrors, CreateBoardProposalData, CreateBoardProposalResponses, CreateBoardProposalErrors, VoteProposalData, VoteProposalResponses, VoteProposalErrors, ListBoardCommentsData, ListBoardCommentsResponses, ListBoardCommentsErrors, CreateBoardCommentData, CreateBoardCommentResponses, CreateBoardCommentErrors } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health check
 * Returns the service health status. No authentication required.
 */
export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetHealthResponses, unknown, ThrowOnError>({
        url: '/v1/api/health',
        ...options
    });
};

/**
 * GitHub webhook
 * Receives GitHub webhook events. Validates request using X-Hub-Signature-256.
 */
export const handleGithubWebhook = <ThrowOnError extends boolean = false>(options: Options<HandleGithubWebhookData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<HandleGithubWebhookResponses, HandleGithubWebhookErrors, ThrowOnError>({
        security: [
            {
                name: 'X-Hub-Signature-256',
                type: 'apiKey'
            }
        ],
        url: '/v1/api/github/webhook',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * List runs
 * List execution runs with optional pagination.
 */
export const listRuns = <ThrowOnError extends boolean = false>(options?: Options<ListRunsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ListRunsResponses, ListRunsErrors, ThrowOnError>({
        security: [
            {
                name: 'X-Api-Key',
                type: 'apiKey'
            }
        ],
        url: '/v1/api/runs',
        ...options
    });
};

/**
 * Create run
 * Create a new execution run for an issue.
 */
export const createRun = <ThrowOnError extends boolean = false>(options: Options<CreateRunData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateRunResponses, CreateRunErrors, ThrowOnError>({
        security: [
            {
                name: 'X-Api-Key',
                type: 'apiKey'
            }
        ],
        url: '/v1/api/runs',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get run
 * Get a single run by ID.
 */
export const getRun = <ThrowOnError extends boolean = false>(options: Options<GetRunData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetRunResponses, GetRunErrors, ThrowOnError>({
        security: [
            {
                name: 'X-Api-Key',
                type: 'apiKey'
            }
        ],
        url: '/v1/api/runs/{id}',
        ...options
    });
};

/**
 * Retry run
 * Retry a failed run.
 */
export const retryRun = <ThrowOnError extends boolean = false>(options: Options<RetryRunData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<RetryRunResponses, RetryRunErrors, ThrowOnError>({
        security: [
            {
                name: 'X-Api-Key',
                type: 'apiKey'
            }
        ],
        url: '/v1/api/runs/{id}/retry',
        ...options
    });
};

/**
 * Cancel run
 * Cancel a running execution.
 */
export const cancelRun = <ThrowOnError extends boolean = false>(options: Options<CancelRunData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CancelRunResponses, CancelRunErrors, ThrowOnError>({
        security: [
            {
                name: 'X-Api-Key',
                type: 'apiKey'
            }
        ],
        url: '/v1/api/runs/{id}/cancel',
        ...options
    });
};

/**
 * List repos
 * List all repository configurations.
 */
export const listRepos = <ThrowOnError extends boolean = false>(options?: Options<ListReposData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ListReposResponses, ListReposErrors, ThrowOnError>({
        security: [
            {
                name: 'X-Api-Key',
                type: 'apiKey'
            }
        ],
        url: '/v1/api/repos',
        ...options
    });
};

/**
 * Delete repo config
 * Delete configuration for a repository.
 */
export const deleteRepoConfig = <ThrowOnError extends boolean = false>(options: Options<DeleteRepoConfigData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteRepoConfigResponses, DeleteRepoConfigErrors, ThrowOnError>({
        security: [
            {
                name: 'X-Api-Key',
                type: 'apiKey'
            }
        ],
        url: '/v1/api/repos/{owner}/{repo}/config',
        ...options
    });
};

/**
 * Get repo config
 * Get configuration for a specific repository.
 */
export const getRepoConfig = <ThrowOnError extends boolean = false>(options: Options<GetRepoConfigData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetRepoConfigResponses, GetRepoConfigErrors, ThrowOnError>({
        security: [
            {
                name: 'X-Api-Key',
                type: 'apiKey'
            }
        ],
        url: '/v1/api/repos/{owner}/{repo}/config',
        ...options
    });
};

/**
 * Update repo config
 * Update configuration for a repository. All fields are optional.
 */
export const updateRepoConfig = <ThrowOnError extends boolean = false>(options: Options<UpdateRepoConfigData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<UpdateRepoConfigResponses, UpdateRepoConfigErrors, ThrowOnError>({
        security: [
            {
                name: 'X-Api-Key',
                type: 'apiKey'
            }
        ],
        url: '/v1/api/repos/{owner}/{repo}/config',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * List roadmap items
 * List all proposals for a repo sorted by vote count (team view).
 */
export const listRoadmapItems = <ThrowOnError extends boolean = false>(options: Options<ListRoadmapItemsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<ListRoadmapItemsResponses, ListRoadmapItemsErrors, ThrowOnError>({
        security: [
            {
                name: 'X-Api-Key',
                type: 'apiKey'
            }
        ],
        url: '/v1/api/repos/{owner}/{repo}/roadmap',
        ...options
    });
};

/**
 * Update proposal status
 * Update the status of a proposal (team only).
 */
export const updateProposalStatus = <ThrowOnError extends boolean = false>(options: Options<UpdateProposalStatusData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<UpdateProposalStatusResponses, UpdateProposalStatusErrors, ThrowOnError>({
        security: [
            {
                name: 'X-Api-Key',
                type: 'apiKey'
            }
        ],
        url: '/v1/api/repos/{owner}/{repo}/proposals/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * List proposals (public)
 * List all proposals for a public board, sorted by vote count.
 */
export const listBoardProposals = <ThrowOnError extends boolean = false>(options: Options<ListBoardProposalsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<ListBoardProposalsResponses, ListBoardProposalsErrors, ThrowOnError>({
        url: '/board/{owner}/{repo}/proposals',
        ...options
    });
};

/**
 * Create proposal (public)
 * Submit a new feature request proposal on a public board.
 */
export const createBoardProposal = <ThrowOnError extends boolean = false>(options: Options<CreateBoardProposalData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateBoardProposalResponses, CreateBoardProposalErrors, ThrowOnError>({
        url: '/board/{owner}/{repo}/proposals',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Vote on proposal (public)
 * Increment the vote count for a proposal.
 */
export const voteProposal = <ThrowOnError extends boolean = false>(options: Options<VoteProposalData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<VoteProposalResponses, VoteProposalErrors, ThrowOnError>({
        url: '/board/{owner}/{repo}/proposals/{id}/vote',
        ...options
    });
};

/**
 * List comments (public)
 * List all comments for a proposal on a public board.
 */
export const listBoardComments = <ThrowOnError extends boolean = false>(options: Options<ListBoardCommentsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<ListBoardCommentsResponses, ListBoardCommentsErrors, ThrowOnError>({
        url: '/board/{owner}/{repo}/proposals/{id}/comments',
        ...options
    });
};

/**
 * Create comment (public)
 * Post a comment on a proposal on a public board.
 */
export const createBoardComment = <ThrowOnError extends boolean = false>(options: Options<CreateBoardCommentData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateBoardCommentResponses, CreateBoardCommentErrors, ThrowOnError>({
        url: '/board/{owner}/{repo}/proposals/{id}/comments',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};