// This file is auto-generated by @hey-api/openapi-ts

export type _Error = {
    /**
     * Error message
     */
    error: string;
};

export type Run = {
    id: number;
    owner: string;
    repo: string;
    issue_number: number;
    status: 'pending' | 'in_progress' | 'success' | 'failed' | 'cancelled';
    branch?: string | null;
    pr_url?: string | null;
    error?: string | null;
    created_at: string;
    updated_at: string;
};

export type CreateRunRequest = {
    owner: string;
    repo: string;
    issue_number: number;
};

export type RepoConfig = {
    id: number;
    owner: string;
    repo: string;
    label_approved: string;
    label_in_progress: string;
    label_done: string;
    label_failed: string;
    label_feature_request: string;
    vote_threshold: number;
    timeout_minutes: number;
    max_budget_usd: number;
    /**
     * Whether the community board is publicly accessible
     */
    is_board_public: boolean;
    created_at: string;
    updated_at: string;
};

/**
 * All fields are optional. Only provided fields will be updated.
 */
export type UpdateRepoConfigRequest = {
    label_approved?: string;
    label_in_progress?: string;
    label_done?: string;
    label_failed?: string;
    label_feature_request?: string;
    vote_threshold?: number;
    timeout_minutes?: number;
    max_budget_usd?: number;
    /**
     * API key for Anthropic (stored securely, not returned in responses)
     */
    anthropic_api_key?: string;
    /**
     * Whether the community board is publicly accessible
     */
    is_board_public?: boolean;
};

export type Proposal = {
    id: number;
    owner: string;
    repo: string;
    title: string;
    description: string;
    vote_count: number;
    status: 'open' | 'planned' | 'done';
    created_at: string;
    updated_at: string;
};

export type ProposalComment = {
    id: number;
    proposal_id: number;
    body: string;
    author_name: string;
    created_at: string;
};

export type CreateProposalRequest = {
    title: string;
    description?: string;
};

export type CreateCommentRequest = {
    body: string;
    /**
     * Display name (defaults to "Anonymous" if omitted)
     */
    author_name?: string;
};

export type UpdateProposalStatusRequest = {
    status: 'open' | 'planned' | 'done';
};

/**
 * Run ID
 */
export type RunId = number;

/**
 * Repository owner (e.g. GitHub org or username)
 */
export type Owner = string;

/**
 * Repository name
 */
export type Repo = string;

/**
 * Proposal ID
 */
export type ProposalId = number;

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/api/health';
};

export type GetHealthResponses = {
    /**
     * Service is healthy
     */
    200: {
        status: string;
    };
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type HandleGithubWebhookData = {
    /**
     * GitHub webhook event payload (varies by event type)
     */
    body: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/v1/api/github/webhook';
};

export type HandleGithubWebhookErrors = {
    /**
     * Invalid or missing signature
     */
    401: _Error;
};

export type HandleGithubWebhookError = HandleGithubWebhookErrors[keyof HandleGithubWebhookErrors];

export type HandleGithubWebhookResponses = {
    /**
     * Webhook processed successfully
     */
    200: unknown;
};

export type ListRunsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Maximum number of runs to return (1-100)
         */
        limit?: number;
        /**
         * Number of runs to skip for pagination
         */
        offset?: number;
    };
    url: '/v1/api/runs';
};

export type ListRunsErrors = {
    /**
     * Missing or invalid API key
     */
    401: _Error;
    /**
     * API key is not configured on the server
     */
    503: _Error;
};

export type ListRunsError = ListRunsErrors[keyof ListRunsErrors];

export type ListRunsResponses = {
    /**
     * List of runs
     */
    200: Array<Run>;
};

export type ListRunsResponse = ListRunsResponses[keyof ListRunsResponses];

export type CreateRunData = {
    body: CreateRunRequest;
    path?: never;
    query?: never;
    url: '/v1/api/runs';
};

export type CreateRunErrors = {
    /**
     * Invalid request
     */
    400: _Error;
    /**
     * Missing or invalid API key
     */
    401: _Error;
    /**
     * Run already exists for this issue
     */
    409: _Error;
    /**
     * API key is not configured on the server
     */
    503: _Error;
};

export type CreateRunError = CreateRunErrors[keyof CreateRunErrors];

export type CreateRunResponses = {
    /**
     * Run created
     */
    201: Run;
};

export type CreateRunResponse = CreateRunResponses[keyof CreateRunResponses];

export type GetRunData = {
    body?: never;
    path: {
        /**
         * Run ID
         */
        id: number;
    };
    query?: never;
    url: '/v1/api/runs/{id}';
};

export type GetRunErrors = {
    /**
     * Invalid request
     */
    400: _Error;
    /**
     * Missing or invalid API key
     */
    401: _Error;
    /**
     * Run not found
     */
    404: _Error;
    /**
     * API key is not configured on the server
     */
    503: _Error;
};

export type GetRunError = GetRunErrors[keyof GetRunErrors];

export type GetRunResponses = {
    /**
     * Run details
     */
    200: Run;
};

export type GetRunResponse = GetRunResponses[keyof GetRunResponses];

export type RetryRunData = {
    body?: never;
    path: {
        /**
         * Run ID
         */
        id: number;
    };
    query?: never;
    url: '/v1/api/runs/{id}/retry';
};

export type RetryRunErrors = {
    /**
     * Invalid request
     */
    400: _Error;
    /**
     * Missing or invalid API key
     */
    401: _Error;
    /**
     * Execution is not in a retryable state
     */
    409: _Error;
    /**
     * API key is not configured on the server
     */
    503: _Error;
};

export type RetryRunError = RetryRunErrors[keyof RetryRunErrors];

export type RetryRunResponses = {
    /**
     * Run retried
     */
    200: Run;
};

export type RetryRunResponse = RetryRunResponses[keyof RetryRunResponses];

export type CancelRunData = {
    body?: never;
    path: {
        /**
         * Run ID
         */
        id: number;
    };
    query?: never;
    url: '/v1/api/runs/{id}/cancel';
};

export type CancelRunErrors = {
    /**
     * Invalid request
     */
    400: _Error;
    /**
     * Missing or invalid API key
     */
    401: _Error;
    /**
     * Execution is not in a cancellable state
     */
    409: _Error;
    /**
     * API key is not configured on the server
     */
    503: _Error;
};

export type CancelRunError = CancelRunErrors[keyof CancelRunErrors];

export type CancelRunResponses = {
    /**
     * Run cancelled
     */
    200: Run;
};

export type CancelRunResponse = CancelRunResponses[keyof CancelRunResponses];

export type ListReposData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/api/repos';
};

export type ListReposErrors = {
    /**
     * Missing or invalid API key
     */
    401: _Error;
    /**
     * API key is not configured on the server
     */
    503: _Error;
};

export type ListReposError = ListReposErrors[keyof ListReposErrors];

export type ListReposResponses = {
    /**
     * List of repo configurations
     */
    200: Array<RepoConfig>;
};

export type ListReposResponse = ListReposResponses[keyof ListReposResponses];

export type DeleteRepoConfigData = {
    body?: never;
    path: {
        /**
         * Repository owner (e.g. GitHub org or username)
         */
        owner: string;
        /**
         * Repository name
         */
        repo: string;
    };
    query?: never;
    url: '/v1/api/repos/{owner}/{repo}/config';
};

export type DeleteRepoConfigErrors = {
    /**
     * Missing or invalid API key
     */
    401: _Error;
    /**
     * API key is not configured on the server
     */
    503: _Error;
};

export type DeleteRepoConfigError = DeleteRepoConfigErrors[keyof DeleteRepoConfigErrors];

export type DeleteRepoConfigResponses = {
    /**
     * Config deleted
     */
    204: void;
};

export type DeleteRepoConfigResponse = DeleteRepoConfigResponses[keyof DeleteRepoConfigResponses];

export type GetRepoConfigData = {
    body?: never;
    path: {
        /**
         * Repository owner (e.g. GitHub org or username)
         */
        owner: string;
        /**
         * Repository name
         */
        repo: string;
    };
    query?: never;
    url: '/v1/api/repos/{owner}/{repo}/config';
};

export type GetRepoConfigErrors = {
    /**
     * Missing or invalid API key
     */
    401: _Error;
    /**
     * Repo config not found
     */
    404: _Error;
    /**
     * API key is not configured on the server
     */
    503: _Error;
};

export type GetRepoConfigError = GetRepoConfigErrors[keyof GetRepoConfigErrors];

export type GetRepoConfigResponses = {
    /**
     * Repo configuration
     */
    200: RepoConfig;
};

export type GetRepoConfigResponse = GetRepoConfigResponses[keyof GetRepoConfigResponses];

export type UpdateRepoConfigData = {
    body?: UpdateRepoConfigRequest;
    path: {
        /**
         * Repository owner (e.g. GitHub org or username)
         */
        owner: string;
        /**
         * Repository name
         */
        repo: string;
    };
    query?: never;
    url: '/v1/api/repos/{owner}/{repo}/config';
};

export type UpdateRepoConfigErrors = {
    /**
     * Invalid request
     */
    400: _Error;
    /**
     * Missing or invalid API key
     */
    401: _Error;
    /**
     * API key is not configured on the server
     */
    503: _Error;
};

export type UpdateRepoConfigError = UpdateRepoConfigErrors[keyof UpdateRepoConfigErrors];

export type UpdateRepoConfigResponses = {
    /**
     * Config updated
     */
    200: RepoConfig;
};

export type UpdateRepoConfigResponse = UpdateRepoConfigResponses[keyof UpdateRepoConfigResponses];

export type ListRoadmapItemsData = {
    body?: never;
    path: {
        /**
         * Repository owner (e.g. GitHub org or username)
         */
        owner: string;
        /**
         * Repository name
         */
        repo: string;
    };
    query?: never;
    url: '/v1/api/repos/{owner}/{repo}/roadmap';
};

export type ListRoadmapItemsErrors = {
    /**
     * Missing or invalid API key
     */
    401: _Error;
    /**
     * API key is not configured on the server
     */
    503: _Error;
};

export type ListRoadmapItemsError = ListRoadmapItemsErrors[keyof ListRoadmapItemsErrors];

export type ListRoadmapItemsResponses = {
    /**
     * List of proposals
     */
    200: Array<Proposal>;
};

export type ListRoadmapItemsResponse = ListRoadmapItemsResponses[keyof ListRoadmapItemsResponses];

export type UpdateProposalStatusData = {
    body: UpdateProposalStatusRequest;
    path: {
        /**
         * Repository owner (e.g. GitHub org or username)
         */
        owner: string;
        /**
         * Repository name
         */
        repo: string;
        /**
         * Proposal ID
         */
        id: number;
    };
    query?: never;
    url: '/v1/api/repos/{owner}/{repo}/proposals/{id}';
};

export type UpdateProposalStatusErrors = {
    /**
     * Invalid request
     */
    400: _Error;
    /**
     * Missing or invalid API key
     */
    401: _Error;
    /**
     * Proposal not found
     */
    404: _Error;
    /**
     * API key is not configured on the server
     */
    503: _Error;
};

export type UpdateProposalStatusError = UpdateProposalStatusErrors[keyof UpdateProposalStatusErrors];

export type UpdateProposalStatusResponses = {
    /**
     * Proposal updated
     */
    200: Proposal;
};

export type UpdateProposalStatusResponse = UpdateProposalStatusResponses[keyof UpdateProposalStatusResponses];

export type ListBoardProposalsData = {
    body?: never;
    path: {
        /**
         * Repository owner (e.g. GitHub org or username)
         */
        owner: string;
        /**
         * Repository name
         */
        repo: string;
    };
    query?: never;
    url: '/board/{owner}/{repo}/proposals';
};

export type ListBoardProposalsErrors = {
    /**
     * Board is not public
     */
    403: _Error;
};

export type ListBoardProposalsError = ListBoardProposalsErrors[keyof ListBoardProposalsErrors];

export type ListBoardProposalsResponses = {
    /**
     * List of proposals
     */
    200: Array<Proposal>;
};

export type ListBoardProposalsResponse = ListBoardProposalsResponses[keyof ListBoardProposalsResponses];

export type CreateBoardProposalData = {
    body: CreateProposalRequest;
    path: {
        /**
         * Repository owner (e.g. GitHub org or username)
         */
        owner: string;
        /**
         * Repository name
         */
        repo: string;
    };
    query?: never;
    url: '/board/{owner}/{repo}/proposals';
};

export type CreateBoardProposalErrors = {
    /**
     * Invalid request
     */
    400: _Error;
    /**
     * Board is not public
     */
    403: _Error;
};

export type CreateBoardProposalError = CreateBoardProposalErrors[keyof CreateBoardProposalErrors];

export type CreateBoardProposalResponses = {
    /**
     * Proposal created
     */
    201: Proposal;
};

export type CreateBoardProposalResponse = CreateBoardProposalResponses[keyof CreateBoardProposalResponses];

export type VoteProposalData = {
    body?: never;
    path: {
        /**
         * Repository owner (e.g. GitHub org or username)
         */
        owner: string;
        /**
         * Repository name
         */
        repo: string;
        /**
         * Proposal ID
         */
        id: number;
    };
    query?: never;
    url: '/board/{owner}/{repo}/proposals/{id}/vote';
};

export type VoteProposalErrors = {
    /**
     * Invalid request
     */
    400: _Error;
    /**
     * Board is not public
     */
    403: _Error;
    /**
     * Proposal not found
     */
    404: _Error;
};

export type VoteProposalError = VoteProposalErrors[keyof VoteProposalErrors];

export type VoteProposalResponses = {
    /**
     * Vote recorded
     */
    200: Proposal;
};

export type VoteProposalResponse = VoteProposalResponses[keyof VoteProposalResponses];

export type ListBoardCommentsData = {
    body?: never;
    path: {
        /**
         * Repository owner (e.g. GitHub org or username)
         */
        owner: string;
        /**
         * Repository name
         */
        repo: string;
        /**
         * Proposal ID
         */
        id: number;
    };
    query?: never;
    url: '/board/{owner}/{repo}/proposals/{id}/comments';
};

export type ListBoardCommentsErrors = {
    /**
     * Invalid request
     */
    400: _Error;
    /**
     * Board is not public
     */
    403: _Error;
};

export type ListBoardCommentsError = ListBoardCommentsErrors[keyof ListBoardCommentsErrors];

export type ListBoardCommentsResponses = {
    /**
     * List of comments
     */
    200: Array<ProposalComment>;
};

export type ListBoardCommentsResponse = ListBoardCommentsResponses[keyof ListBoardCommentsResponses];

export type CreateBoardCommentData = {
    body: CreateCommentRequest;
    path: {
        /**
         * Repository owner (e.g. GitHub org or username)
         */
        owner: string;
        /**
         * Repository name
         */
        repo: string;
        /**
         * Proposal ID
         */
        id: number;
    };
    query?: never;
    url: '/board/{owner}/{repo}/proposals/{id}/comments';
};

export type CreateBoardCommentErrors = {
    /**
     * Invalid request
     */
    400: _Error;
    /**
     * Board is not public
     */
    403: _Error;
};

export type CreateBoardCommentError = CreateBoardCommentErrors[keyof CreateBoardCommentErrors];

export type CreateBoardCommentResponses = {
    /**
     * Comment created
     */
    201: ProposalComment;
};

export type CreateBoardCommentResponse = CreateBoardCommentResponses[keyof CreateBoardCommentResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};