// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: executions.sql

package store

import (
	"context"
)

const createExecution = `-- name: CreateExecution :one
INSERT INTO executions (owner, repo, issue_number, status)
VALUES ($1, $2, $3, 'pending')
RETURNING id, owner, repo, issue_number, status, branch, pr_url, error, created_at, updated_at
`

type CreateExecutionParams struct {
	Owner       string
	Repo        string
	IssueNumber int32
}

func (q *Queries) CreateExecution(ctx context.Context, arg CreateExecutionParams) (Execution, error) {
	row := q.db.QueryRow(ctx, createExecution, arg.Owner, arg.Repo, arg.IssueNumber)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Repo,
		&i.IssueNumber,
		&i.Status,
		&i.Branch,
		&i.PrUrl,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateExecutionFailed = `-- name: UpdateExecutionFailed :one
UPDATE executions
SET status = 'failed', error = $1, updated_at = now()
WHERE id = $2
RETURNING id, owner, repo, issue_number, status, branch, pr_url, error, created_at, updated_at
`

type UpdateExecutionFailedParams struct {
	Error *string
	ID    int64
}

func (q *Queries) UpdateExecutionFailed(ctx context.Context, arg UpdateExecutionFailedParams) (Execution, error) {
	row := q.db.QueryRow(ctx, updateExecutionFailed, arg.Error, arg.ID)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Repo,
		&i.IssueNumber,
		&i.Status,
		&i.Branch,
		&i.PrUrl,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateExecutionInProgress = `-- name: UpdateExecutionInProgress :one
UPDATE executions
SET status = 'in_progress', branch = $1, updated_at = now()
WHERE id = $2
RETURNING id, owner, repo, issue_number, status, branch, pr_url, error, created_at, updated_at
`

type UpdateExecutionInProgressParams struct {
	Branch *string
	ID     int64
}

func (q *Queries) UpdateExecutionInProgress(ctx context.Context, arg UpdateExecutionInProgressParams) (Execution, error) {
	row := q.db.QueryRow(ctx, updateExecutionInProgress, arg.Branch, arg.ID)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Repo,
		&i.IssueNumber,
		&i.Status,
		&i.Branch,
		&i.PrUrl,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateExecutionSuccess = `-- name: UpdateExecutionSuccess :one
UPDATE executions
SET status = 'success', pr_url = $1, updated_at = now()
WHERE id = $2
RETURNING id, owner, repo, issue_number, status, branch, pr_url, error, created_at, updated_at
`

type UpdateExecutionSuccessParams struct {
	PrUrl *string
	ID    int64
}

func (q *Queries) UpdateExecutionSuccess(ctx context.Context, arg UpdateExecutionSuccessParams) (Execution, error) {
	row := q.db.QueryRow(ctx, updateExecutionSuccess, arg.PrUrl, arg.ID)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Repo,
		&i.IssueNumber,
		&i.Status,
		&i.Branch,
		&i.PrUrl,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
