// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Execution struct {
	ID          int64
	Owner       string
	Repo        string
	IssueNumber int32
	Status      string
	Branch      *string
	PrUrl       *string
	Error       *string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type IssueVote struct {
	ID          int64
	Owner       string
	Repo        string
	IssueNumber int32
	VoteCount   int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type RepoConfig struct {
	ID                  int64
	Owner               string
	Repo                string
	LabelApproved       *string
	LabelInProgress     *string
	LabelDone           *string
	LabelFailed         *string
	LabelFeatureRequest *string
	VoteThreshold       *int32
	TimeoutMinutes      *int32
	MaxBudgetUsd        pgtype.Numeric
	AnthropicApiKey     *string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}
