// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/didrikolofsson/github-vote-llm/internal/github (interfaces: AppClientIface)
//
// Generated by this command:
//
//	mockgen -destination=internal/github/mock_app_client.go -package=github github.com/didrikolofsson/github-vote-llm/internal/github AppClientIface
//

// Package github is a generated GoMock package.
package github

import (
	context "context"
	reflect "reflect"

	github "github.com/google/go-github/v84/github"
	gomock "go.uber.org/mock/gomock"
)

// MockAppClientIface is a mock of AppClientIface interface.
type MockAppClientIface struct {
	ctrl     *gomock.Controller
	recorder *MockAppClientIfaceMockRecorder
	isgomock struct{}
}

// MockAppClientIfaceMockRecorder is the mock recorder for MockAppClientIface.
type MockAppClientIfaceMockRecorder struct {
	mock *MockAppClientIface
}

// NewMockAppClientIface creates a new mock instance.
func NewMockAppClientIface(ctrl *gomock.Controller) *MockAppClientIface {
	mock := &MockAppClientIface{ctrl: ctrl}
	mock.recorder = &MockAppClientIfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppClientIface) EXPECT() *MockAppClientIfaceMockRecorder {
	return m.recorder
}

// AppAPIClient mocks base method.
func (m *MockAppClientIface) AppAPIClient() (*github.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppAPIClient")
	ret0, _ := ret[0].(*github.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AppAPIClient indicates an expected call of AppAPIClient.
func (mr *MockAppClientIfaceMockRecorder) AppAPIClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppAPIClient", reflect.TypeOf((*MockAppClientIface)(nil).AppAPIClient))
}

// InstallationClient mocks base method.
func (m *MockAppClientIface) InstallationClient(ctx context.Context, installationID int64) (*github.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InstallationClient", ctx, installationID)
	ret0, _ := ret[0].(*github.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InstallationClient indicates an expected call of InstallationClient.
func (mr *MockAppClientIfaceMockRecorder) InstallationClient(ctx, installationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InstallationClient", reflect.TypeOf((*MockAppClientIface)(nil).InstallationClient), ctx, installationID)
}

// InstallationToken mocks base method.
func (m *MockAppClientIface) InstallationToken(ctx context.Context, installationID int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InstallationToken", ctx, installationID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InstallationToken indicates an expected call of InstallationToken.
func (mr *MockAppClientIfaceMockRecorder) InstallationToken(ctx, installationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InstallationToken", reflect.TypeOf((*MockAppClientIface)(nil).InstallationToken), ctx, installationID)
}
