name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci-backend:
    name: Test & Build (backend)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: server/go.mod

      - uses: actions/setup-node@v4
        with:
          node-version: "24"

      - uses: pnpm/action-setup@v4
        with:
          version: 10.18.3

      - name: Test
        run: pnpm test-server

      - name: Build
        run: pnpm build-server

  ci-client:
    name: Build (client)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "24"

      - uses: pnpm/action-setup@v4
        with:
          version: 10.18.3

      - name: Install root dependencies
        run: pnpm install

      - name: Install client dependencies
        run: pnpm install-client

      - name: Build
        run: pnpm build-client
